"""Theme taxonomy for the IndusInd pulse V2: the same ids, labels, owners, pillars, rungs and default actions as the HDFC
pulse V2, so the cloned screens read the same structure."""

THEMES = [
    {
        "id": "app_praise",
        "label": "Where customers praise us: quick, easy app journeys",
        "group": "App and digital",
        "pillar": "experience",
        "owner": "digital",
        "owner_label": "Digital",
        "business": "retail_banking",
        "definition": "Positive app reviews: easy, fast, useful, smooth.",
        "rung": "Voice",
        "action": "Monitor"
    },
    {
        "id": "app_speed_crash",
        "label": "App speed, loading and crashes",
        "group": "App and digital",
        "pillar": "availability",
        "owner": "digital",
        "owner_label": "Digital",
        "business": "retail_banking",
        "definition": "App is slow, will not open, freezes, crashes or shows 'something went wrong'.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "general_dissatisfaction",
        "label": "General dissatisfaction",
        "group": "Other",
        "pillar": "experience",
        "owner": "cx",
        "owner_label": "CX",
        "business": "retail_banking",
        "definition": "Negative without a specific issue: 'worst bank', 'pathetic service'.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "app_usability",
        "label": "App features and usability",
        "group": "App and digital",
        "pillar": "experience",
        "owner": "digital",
        "owner_label": "Digital",
        "business": "retail_banking",
        "definition": "Missing features, confusing design, keyboard, statement download in app, IPO ASBA, card-only login, dark mode, language.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "card_eligibility_upgrade",
        "label": "Card eligibility, upgrade and LTF requests",
        "group": "Cards",
        "pillar": "experience",
        "owner": "cards",
        "owner_label": "Cards",
        "business": "cards",
        "definition": "Eligibility criteria (Pioneer, Legend, Celesta), upgrade paths, lifetime-free requests, pre-approved offers.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "card_variant_migration",
        "label": "Card variant migration and forced upgrade",
        "group": "Cards",
        "pillar": "experience",
        "owner": "cards",
        "owner_label": "Cards",
        "business": "cards",
        "definition": "Card variants phased out or converted (EazyDiner, Avios, Jio-bp and other co-brand changes); forced upgrade or downgrade.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "complaint_handling",
        "label": "Complaints closed without resolution",
        "group": "Service",
        "pillar": "experience",
        "owner": "cx",
        "owner_label": "CX",
        "business": "retail_banking",
        "definition": "Complaints or tickets closed without a fix, generic replies, having to repeat the complaint, DMs with no outcome.",
        "rung": "RBI Ombudsman",
        "action": "Update and close"
    },
    {
        "id": "login_mpin",
        "label": "Login, MPIN and registration",
        "group": "App and digital",
        "pillar": "availability",
        "owner": "digital",
        "owner_label": "Digital",
        "business": "retail_banking",
        "definition": "Cannot log in, register or verify; MPIN, password, OTP or SMS verification, device binding, forced re-registration.",
        "rung": "Repeat",
        "action": "Route with evidence"
    },
    {
        "id": "rewards_value",
        "label": "Rewards value, devaluation and caps",
        "group": "Cards",
        "pillar": "experience",
        "owner": "cards",
        "owner_label": "Cards",
        "business": "cards",
        "definition": "Reward-point value, devaluation, Indus Moments redemption, milestone and accelerated-reward changes, spend criteria.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "care_unreachable",
        "label": "Customer care unreachable or unhelpful",
        "group": "Service",
        "pillar": "availability",
        "owner": "cx",
        "owner_label": "CX",
        "business": "retail_banking",
        "definition": "Cannot reach phone banking or chat, long waits, IVR loops, unhelpful chatbot or agents.",
        "rung": "RBI Ombudsman",
        "action": "Route with evidence"
    },
    {
        "id": "card_application",
        "label": "Card application, rejection and verification",
        "group": "Cards",
        "pillar": "experience",
        "owner": "cards",
        "owner_label": "Cards",
        "business": "cards",
        "definition": "Applications rejected, stuck in verification, video KYC, document checks.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "product_advice",
        "label": "Product questions and advice-seeking",
        "group": "Other",
        "pillar": "experience",
        "owner": "product",
        "owner_label": "Product",
        "business": "retail_banking",
        "definition": "Neutral questions and comparisons: which card, is this worth it, how to apply.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "device_security_block",
        "label": "Device security blocks and false alerts",
        "group": "App and digital",
        "pillar": "availability",
        "owner": "digital",
        "owner_label": "Digital",
        "business": "retail_banking",
        "definition": "App refuses to run or disables itself because of device checks: developer options, USB debugging, root, 'security violation', 'device not compatible', risky-app warnings.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "new_app_release",
        "label": "New app and update experience",
        "group": "App and digital",
        "pillar": "availability",
        "owner": "digital",
        "owner_label": "Digital",
        "business": "retail_banking",
        "definition": "Reactions to the INDIE app or a recent update: migration, old app better, features lost after update.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "account_freeze",
        "label": "Account debit freezes and blocks",
        "group": "Service",
        "pillar": "availability",
        "owner": "operations",
        "owner_label": "Operations",
        "business": "retail_banking",
        "definition": "Accounts frozen or debit-blocked (KYC, undelivered letters, law-enforcement holds, suspicious activity), liens and holds.",
        "rung": "RBI Ombudsman",
        "action": "Set a new date"
    },
    {
        "id": "card_fees_charges",
        "label": "Card fees and charges",
        "group": "Cards",
        "pillar": "experience",
        "owner": "cards",
        "owner_label": "Cards",
        "business": "cards",
        "definition": "Annual and renewal fees, late fees, finance charges, no-cost EMI charges on cards.",
        "rung": "RBI Ombudsman",
        "action": "Route with evidence"
    },
    {
        "id": "reward_redemption",
        "label": "Reward redemption and vouchers",
        "group": "Cards",
        "pillar": "experience",
        "owner": "cards",
        "owner_label": "Cards",
        "business": "cards",
        "definition": "Redeeming points, vouchers not available or not received, milestone vouchers pending.",
        "rung": "RBI Ombudsman",
        "action": "Set a new date"
    },
    {
        "id": "loan_processing",
        "label": "Loan processing and disbursal",
        "group": "Loans",
        "pillar": "experience",
        "owner": "loans",
        "owner_label": "Loans",
        "business": "loans",
        "definition": "Loan applications, sanction, disbursal delays, valuation and verification, documentation.",
        "rung": "RBI Ombudsman",
        "action": "Monitor"
    },
    {
        "id": "upi_failures",
        "label": "UPI payments failing or pending",
        "group": "Payments",
        "pillar": "availability",
        "owner": "payments",
        "owner_label": "Payments",
        "business": "payments",
        "definition": "UPI payments failing, pending, declined or blocked; UPI PIN; UPI limits.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "card_limit",
        "label": "Credit limit",
        "group": "Cards",
        "pillar": "experience",
        "owner": "cards",
        "owner_label": "Cards",
        "business": "cards",
        "definition": "Credit limit too low, limit enhancement, limit cut.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "account_opening",
        "label": "Account opening and product conversion",
        "group": "Service",
        "pillar": "experience",
        "owner": "retail",
        "owner_label": "Retail",
        "business": "retail_banking",
        "definition": "Opening savings or current accounts, pending opening, account variant conversion, minimum balance programmes.",
        "rung": "Voice",
        "action": "Set a new date"
    },
    {
        "id": "closure_requests",
        "label": "Account and card closure requests",
        "group": "Service",
        "pillar": "experience",
        "owner": "operations",
        "owner_label": "Operations",
        "business": "retail_banking",
        "definition": "Difficulty closing a card, account or loan; closure pending; charges after closure.",
        "rung": "RBI Ombudsman",
        "action": "Set a new date"
    },
    {
        "id": "failed_txn_reversal",
        "label": "Failed transaction reversal",
        "group": "Payments",
        "pillar": "experience",
        "owner": "payments",
        "owner_label": "Payments",
        "business": "payments",
        "definition": "Money debited but not received or not reversed; ATM cash not dispensed; failed transaction refund.",
        "rung": "Public",
        "action": "Set a new date"
    },
    {
        "id": "unsolicited_calls",
        "label": "Unsolicited sales calls and use of data",
        "group": "Security",
        "pillar": "data_intimacy",
        "owner": "compliance",
        "owner_label": "Compliance",
        "business": "retail_banking",
        "definition": "Repeated sales calls, spam, 'where did you get my number', marketing without consent.",
        "rung": "Public",
        "action": "Route with evidence"
    },
    {
        "id": "offers_deals",
        "label": "Card offers and deals",
        "group": "Other",
        "pillar": "experience",
        "owner": "cards",
        "owner_label": "Cards",
        "business": "cards",
        "definition": "Merchant deals and discounts that mention IndusInd cards (mostly promotional).",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "kyc_updates",
        "label": "KYC, re-KYC and profile updates",
        "group": "Service",
        "pillar": "data_intimacy",
        "owner": "operations",
        "owner_label": "Operations",
        "business": "retail_banking",
        "definition": "KYC and re-KYC, mobile number or address updates, nominee, PAN or Aadhaar linking.",
        "rung": "RBI Ombudsman",
        "action": "Set a new date"
    },
    {
        "id": "branch_service",
        "label": "Branch service and staff behaviour",
        "group": "Service",
        "pillar": "experience",
        "owner": "retail",
        "owner_label": "Retail",
        "business": "retail_banking",
        "definition": "Branch visits, staff behaviour, rudeness, being sent to the home branch.",
        "rung": "Repeat",
        "action": "Route with evidence"
    },
    {
        "id": "fees_charges_bank",
        "label": "Bank charges and hidden fees",
        "group": "Service",
        "pillar": "experience",
        "owner": "retail",
        "owner_label": "Retail",
        "business": "retail_banking",
        "definition": "Account charges, penalties, deductions without intimation, minimum balance penalties.",
        "rung": "RBI Ombudsman",
        "action": "Route with evidence"
    },
    {
        "id": "loan_servicing",
        "label": "EMI and loan account servicing",
        "group": "Loans",
        "pillar": "experience",
        "owner": "loans",
        "owner_label": "Loans",
        "business": "loans",
        "definition": "EMI schedule, EMI debit issues, loan details missing in app, interest-rate resets, part-payments.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "fraud_scam",
        "label": "Fraud and scam calls",
        "group": "Security",
        "pillar": "security",
        "owner": "fraud_cyber",
        "owner_label": "Fraud and Cyber",
        "business": "retail_banking",
        "definition": "Scam calls and messages, impersonation, frauds reported by customers.",
        "rung": "RBI Ombudsman",
        "action": "Route with evidence"
    },
    {
        "id": "mis_selling",
        "label": "Mis-selling and bundled products",
        "group": "Security",
        "pillar": "data_intimacy",
        "owner": "compliance",
        "owner_label": "Compliance",
        "business": "retail_banking",
        "definition": "Insurance or investments pushed with loans or accounts, misleading claims, ULIPs.",
        "rung": "RBI Ombudsman",
        "action": "Route with evidence"
    },
    {
        "id": "recovery_conduct",
        "label": "Recovery and collection conduct",
        "group": "Loans",
        "pillar": "security",
        "owner": "compliance",
        "owner_label": "Compliance",
        "business": "loans",
        "definition": "Recovery agents, collection calls, harassment, legal notices on dues.",
        "rung": "RBI Ombudsman",
        "action": "Route with evidence"
    },
    {
        "id": "rm_service",
        "label": "Relationship manager service",
        "group": "Service",
        "pillar": "experience",
        "owner": "rm",
        "owner_label": "RM",
        "business": "retail_banking",
        "definition": "RM unreachable, RM changes, RM advice and conduct.",
        "rung": "Grievance",
        "action": "Route with evidence"
    },
    {
        "id": "atm_debit_card",
        "label": "Debit card and ATM",
        "group": "Service",
        "pillar": "availability",
        "owner": "operations",
        "owner_label": "Operations",
        "business": "retail_banking",
        "definition": "Debit card issues, ATM limits and failures, debit card variants.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "service_praise",
        "label": "Praise for service",
        "group": "Other",
        "pillar": "experience",
        "owner": "cx",
        "owner_label": "CX",
        "business": "retail_banking",
        "definition": "Customers praising staff, RMs, resolution or the bank overall.",
        "rung": "Voice",
        "action": "Monitor"
    },
    {
        "id": "phishing",
        "label": "Phishing messages and fake links",
        "group": "Security",
        "pillar": "security",
        "owner": "fraud_cyber",
        "owner_label": "Fraud and Cyber",
        "business": "retail_banking",
        "definition": "Phishing SMS, fake links, fake apps, APK files.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "card_dispatch",
        "label": "Card dispatch and delivery",
        "group": "Cards",
        "pillar": "experience",
        "owner": "operations",
        "owner_label": "Operations",
        "business": "cards",
        "definition": "Card or welcome kit not delivered, courier issues, activation after delivery.",
        "rung": "Repeat",
        "action": "Set a new date"
    },
    {
        "id": "dispute_chargeback",
        "label": "Disputes and chargebacks",
        "group": "Service",
        "pillar": "experience",
        "owner": "operations",
        "owner_label": "Operations",
        "business": "cards",
        "definition": "Disputed transactions, chargebacks, dispute outcomes and delays.",
        "rung": "RBI Ombudsman",
        "action": "Set a new date"
    },
    {
        "id": "refund_delay",
        "label": "Refunds not credited",
        "group": "Payments",
        "pillar": "experience",
        "owner": "operations",
        "owner_label": "Operations",
        "business": "payments",
        "definition": "Merchant or excess-payment refunds not credited in time.",
        "rung": "RBI Ombudsman",
        "action": "Notify proactively"
    },
    {
        "id": "unauthorised_txn",
        "label": "Unauthorised transactions",
        "group": "Security",
        "pillar": "security",
        "owner": "fraud_cyber",
        "owner_label": "Fraud and Cyber",
        "business": "cards",
        "definition": "Transactions the customer did not make, card misuse, money stolen from account.",
        "rung": "RBI Ombudsman",
        "action": "Route with evidence"
    },
    {
        "id": "investments_wealth",
        "label": "Investments and mutual funds",
        "group": "Wealth",
        "pillar": "experience",
        "owner": "product",
        "owner_label": "Product",
        "business": "wealth",
        "definition": "Mutual funds, SIPs and portfolio tracking.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "loan_closure_documents",
        "label": "Loan closure, foreclosure and documents",
        "group": "Loans",
        "pillar": "experience",
        "owner": "loans",
        "owner_label": "Loans",
        "business": "loans",
        "definition": "Foreclosure, final settlement, NOC, release of original property documents.",
        "rung": "Repeat",
        "action": "Notify proactively"
    },
    {
        "id": "other",
        "label": "Other",
        "group": "Other",
        "pillar": "experience",
        "owner": "cx",
        "owner_label": "CX",
        "business": "retail_banking",
        "definition": "Anything that fits no theme above.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "netbanking",
        "label": "Net banking",
        "group": "App and digital",
        "pillar": "availability",
        "owner": "digital",
        "owner_label": "Digital",
        "business": "retail_banking",
        "definition": "Net banking access, errors and downtime.",
        "rung": "Voice",
        "action": "Monitor"
    },
    {
        "id": "credit_report",
        "label": "CIBIL and credit-report correction",
        "group": "Security",
        "pillar": "data_intimacy",
        "owner": "compliance",
        "owner_label": "Compliance",
        "business": "retail_banking",
        "definition": "Wrong entries on credit reports, CIBIL score impact, correction delays.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "statements_documents",
        "label": "Statements, certificates and documents",
        "group": "Service",
        "pillar": "experience",
        "owner": "operations",
        "owner_label": "Operations",
        "business": "retail_banking",
        "definition": "Statements, interest certificates, NOC or NDC, physical copies.",
        "rung": "Voice",
        "action": "Set a new date"
    },
    {
        "id": "nri_forex",
        "label": "NRI and forex services",
        "group": "Service",
        "pillar": "experience",
        "owner": "retail",
        "owner_label": "Retail",
        "business": "retail_banking",
        "definition": "NRI accounts, remittances, forex cards.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "merchant_pos",
        "label": "Merchant QR, POS and sound box",
        "group": "Payments",
        "pillar": "availability",
        "owner": "payments",
        "owner_label": "Payments",
        "business": "sme_merchant",
        "definition": "Merchant apps and devices: QR, POS machine, sound box, settlements (INDIE for Business).",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "deposits_rates",
        "label": "Deposits and interest rates",
        "group": "Service",
        "pillar": "experience",
        "owner": "retail",
        "owner_label": "Retail",
        "business": "retail_banking",
        "definition": "Fixed deposits, interest rates, sweep-in.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "market_news",
        "label": "Share price, results and corporate news",
        "group": "Other",
        "pillar": "experience",
        "owner": "cx",
        "owner_label": "CX",
        "business": "corporate",
        "definition": "Stock-market, results and leadership news; not customer experience.",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "trading_securities",
        "label": "Trading and IPO (group company)",
        "group": "Group",
        "pillar": "availability",
        "owner": "product",
        "owner_label": "Product",
        "business": "group_company",
        "definition": "Trading app, orders, IPO, brokerage (group company).",
        "rung": "Voice",
        "action": "Route with evidence"
    },
    {
        "id": "insurance_group",
        "label": "Insurance policies and claims (IndusInd Nippon Life, IndusInd General)",
        "group": "Group",
        "pillar": "experience",
        "owner": "product",
        "owner_label": "Product",
        "business": "group_company",
        "definition": "Policy servicing, claims, premiums, surrender (group companies).",
        "rung": "Voice",
        "action": "Route with evidence"
    }
]
