import {
  ClaimTaxonomyItem,
  EmptyBoxIncident,
  AgentCollusionRisk,
  EscalationData,
  GhostEscalationDetail,
  CoercionAlert,
  AbuseKeyword,
  FraudDashboardStats,
} from './types';
import { FraudInsight } from '@/components/ecom-fraudulent/FraudInsightCards';

// Fraud Risk Score Data
export const fraudRiskScoreData = {
  score: 72.8,
  totalCases: 1747,
  weekChange: 12,
  categories: [
    { name: 'Fulfillment Fraud', value: 18, cases: 349, color: '#EF4444' },
    { name: 'Syndicated Claims', value: 14, cases: 274, color: '#F97316' },
    { name: 'Incentive Fraud', value: 12, cases: 212, color: '#10B981' },
    { name: 'Insider Collusion', value: 13, cases: 224, color: '#A855F7' },
    { name: 'Asset Abuse', value: 11, cases: 187, color: '#3B82F6' },
    { name: 'Brand Extortion', value: 10, cases: 156, color: '#EC4899' },
    { name: '3rd Party Fraud', value: 12, cases: 198, color: '#F59E0B' },
    { name: 'Policy Arbitrage', value: 10, cases: 147, color: '#06B6D4' },
  ],
};

// Fraud Insight Cards Data
export const fraudInsightsData: FraudInsight[] = [
  {
    id: 'FI-001',
    title: 'Delivery Liability Risk',
    severity: 'CRITICAL',
    channels: ['Chat', 'Tickets'],
    detected: '2h ago',
    affected: 2340,
    description: 'Customers claiming "Did Not Receive" for orders showing successful delivery. GPS coordinates mismatch detected in 67% of cases.',
    rootCause: 'Delivery partners are marking delivered early, spoofing GPS, and skipping doorstep proof. Courier incentives reward speed over proof, and drift checks are not enforced.',
    correctiveAction: 'Enforce OTP-at-doorstep plus geo-tagged photo/POD before payout. Alert on >1km drift and hold courier payouts until proof is verified.',
    icon: 'package',
  },
  {
    id: 'FI-002',
    title: 'Internal Policy Violations',
    severity: 'CRITICAL',
    channels: ['Voice', 'Chat'],
    detected: '45m ago',
    affected: 892,
    description: 'Agents bypassing verification steps and issuing refunds without required documentation or manager approval.',
    rootCause: 'Refund overrides lack mandatory audit steps; approvals can be skipped and supporting proof isn’t enforced. Policy training is uneven across shifts.',
    correctiveAction: 'Require dual-auth for refunds >₹5k with enforced document upload. Add real-time policy guardrails and audit logs on every override.',
    icon: 'user',
  },
  {
    id: 'FI-003',
    title: 'Non-Resalable Returns',
    severity: 'HIGH',
    channels: ['Email', 'Tickets'],
    detected: '1h ago',
    affected: 567,
    description: 'Customers returning used items (clothing, electronics) after brief use. Tags removed, signs of wear detected.',
    rootCause: 'Return inspection is visual-only and rushed; no weight, image, or wear scoring before restock. Abuse repeats across the same users and SKUs.',
    correctiveAction: 'Use AI image/weight checks at intake, shorten return windows for high-risk SKUs, and apply restocking fees/blocks on repeat abusers.',
    icon: 'repeat',
  },
  {
    id: 'FI-004',
    title: 'Marketing Budget Waste',
    severity: 'HIGH',
    channels: ['Social Media', 'Chat'],
    detected: '30m ago',
    affected: 1245,
    description: 'Organized groups sharing internal promo codes and exploiting referral system with fake accounts.',
    rootCause: 'Promo codes are not device-bound and leak to social groups; referrals rely on phone/SIM churn with no device or identity proofing.',
    correctiveAction: 'Bind promos to device fingerprint and tighten velocity limits. Add ML fake-account screening on signup/referrals and kill-switch leaked codes.',
    icon: 'shopping',
  },
  {
    id: 'FI-005',
    title: 'Organized Fraud Rings',
    severity: 'CRITICAL',
    channels: ['Tickets', 'Voice'],
    detected: '15m ago',
    affected: 423,
    description: 'Coordinated claims of receiving empty boxes for high-value electronics. Similar phrasing detected across claims.',
    rootCause: 'Likely collusion between claimants and last-mile/warehouse handlers; weight/scan gaps allow box swaps. Reused phrasing suggests a scripted playbook.',
    correctiveAction: 'Add seal/weight verification with photo at handoff, cluster similar claims by route/agent, and auto-suspend risky lanes pending audit.',
    icon: 'package',
  },
  {
    id: 'FI-006',
    title: 'Reputation Ransom Attacks',
    severity: 'HIGH',
    channels: ['Trustpilot', 'X', 'Reddit'],
    detected: '25m ago',
    affected: 187,
    description: 'Customers posting negative reviews within 10 minutes of refund denial. Timestamp correlation between failed tickets and 1-star reviews detected.',
    rootCause: 'Customers weaponize public reviews minutes after denial; there’s no linkage between support outcomes and social blasts, so coercion isn’t flagged.',
    correctiveAction: 'Correlate tickets with social mentions and alert a response pod. Pause concessions until review-risk is cleared; use a rapid rebuttal/offer playbook.',
    icon: 'shopping',
  },
  {
    id: 'FI-007',
    title: 'Refund-as-a-Service (RaaS) Signals',
    severity: 'CRITICAL',
    channels: ['Chat', 'Telegram'],
    detected: '10m ago',
    affected: 312,
    description: 'Professional fraud slang detected in customer communications. Keywords like "DNA", "FTID", and "Boxing" indicate hired refund professionals.',
    rootCause: 'Hired refunders exploit known loopholes; slang (DNA/FTID/boxing) signals pro involvement. No automated screening of these language patterns.',
    correctiveAction: 'Use NLP to flag RaaS slang, auto-route to fraud team, freeze high-risk orders, and require stronger ID/review before payout.',
    icon: 'user',
  },
  {
    id: 'FI-008',
    title: 'Cross-Channel Arbitration',
    severity: 'HIGH',
    channels: ['Chat', 'Email', 'Voice'],
    detected: '35m ago',
    affected: 156,
    description: 'Users receiving denial from chatbot, then calling voice support, then emailing executives within 60 minutes. Hunting for weakest support link.',
    rootCause: 'Policies are enforced differently by bot, phone, and email; there’s no unified trail, so users escalate channel-to-channel until someone says yes.',
    correctiveAction: 'Link cases across channels with a single decision ledger. Alert agents on prior denials and apply a cooldown before re-attempts.',
    icon: 'repeat',
  },
];

// Time Series Data for Claim Taxonomy Chart
export const claimTimeSeriesData = [
  { time: '00', dnr: 45, emptyBox: 32, wardrobing: 18, itemSwitch: 12 },
  { time: '02', dnr: 38, emptyBox: 28, wardrobing: 15, itemSwitch: 10 },
  { time: '04', dnr: 32, emptyBox: 22, wardrobing: 12, itemSwitch: 8 },
  { time: '06', dnr: 48, emptyBox: 35, wardrobing: 20, itemSwitch: 15 },
  { time: '08', dnr: 78, emptyBox: 55, wardrobing: 35, itemSwitch: 22 },
  { time: '10', dnr: 95, emptyBox: 72, wardrobing: 45, itemSwitch: 28 },
  { time: '12', dnr: 88, emptyBox: 68, wardrobing: 42, itemSwitch: 25 },
  { time: '14', dnr: 102, emptyBox: 78, wardrobing: 48, itemSwitch: 32 },
  { time: '16', dnr: 115, emptyBox: 85, wardrobing: 52, itemSwitch: 35 },
  { time: '18', dnr: 92, emptyBox: 70, wardrobing: 40, itemSwitch: 28 },
  { time: '20', dnr: 75, emptyBox: 55, wardrobing: 32, itemSwitch: 20 },
  { time: '22', dnr: 58, emptyBox: 42, wardrobing: 25, itemSwitch: 15 },
];

// Agent Risk Radar Data
export const agentRiskRadarData = {
  data: [
    { category: 'Policy Override', value: 85, fullMark: 100 },
    { category: 'Goodwill Abuse', value: 72, fullMark: 100 },
    { category: 'Escalation Skip', value: 58, fullMark: 100 },
    { category: 'Doc Bypass', value: 78, fullMark: 100 },
    { category: 'VIP Treatment', value: 45, fullMark: 100 },
    { category: 'Secrecy Pattern', value: 62, fullMark: 100 },
  ],
  overallScore: 68,
  riskLevel: 'HIGH',
  topRiskAgent: 'Rajesh M. (EMP-4521)',
  activeVectors: 5,
  aiInsight: '"Policy Override" axis elevated (85/100) due to cluster of unauthorized refunds. Agent EMP-4521 shows 3x deviation from team average.',
};

// Threat Intelligence Grid Data
export const threatIntelligenceData = {
  categories: [
    {
      id: 'TI-001',
      title: 'Legal Threats',
      status: 'CRITICAL' as const,
      count: 156,
      trend: 18,
      subLabel: 'Consumer Forum/FIR',
      icon: 'legal' as const,
    },
    {
      id: 'TI-002',
      title: 'Reputation Leverage Attacks',
      status: 'WARNING' as const,
      count: 89,
      trend: 7,
      subLabel: 'Twitter',
      icon: 'social' as const,
    },
    {
      id: 'TI-003',
      title: 'Social Engineering Attempts',
      status: 'STABLE' as const,
      count: 42,
      trend: -5,
      subLabel: 'Emergency Claims',
      icon: 'urgency' as const,
    },
    {
      id: 'TI-004',
      title: 'Promo Abuse',
      status: 'WARNING' as const,
      count: 234,
      trend: 12,
      subLabel: 'Code/Referral Exploit',
      icon: 'abuse' as const,
    },
  ],
  overallStatus: 'AT RISK' as const,
  aiInsight: '"Legal Threats" have crossed critical threshold (150+ reports/day). 40% originate from repeat claimants with prior Fulfillment Fraud history.',
};

// Widget 1: Claim Taxonomy Data
export const claimTaxonomyData: ClaimTaxonomyItem[] = [
  {
    category: 'Fulfillment Fraud',
    shortLabel: 'Fulfillment',
    count: 847,
    trend: 'up',
    percentChange: 12.4,
  },
  {
    category: 'Syndicated Claims',
    shortLabel: 'Syndicated',
    count: 523,
    trend: 'up',
    percentChange: 8.7,
  },
  {
    category: 'Asset Abuse',
    shortLabel: 'Asset Abuse',
    count: 312,
    trend: 'stable',
    percentChange: 1.2,
  },
  {
    category: 'Incentive Fraud',
    shortLabel: 'Incentive',
    count: 189,
    trend: 'down',
    percentChange: -5.3,
  },
];

// Widget 2: Empty Box Monitor Data
export const emptyBoxIncidents: EmptyBoxIncident[] = [
  {
    id: 'EB-001',
    ticketId: 'TKT-78234',
    itemValue: 89999,
    itemName: 'MacBook Pro 16"',
    detectedKeyword: 'Weight mismatch',
    sentimentScore: -0.87,
    transcriptSnippet: '"The box felt too light when I picked it up. Opened it and found only packing material, no laptop inside..."',
    channel: 'Tickets',
    timestamp: '2024-12-05T10:23:00Z',
    riskLevel: 'CRITICAL',
  },
  {
    id: 'EB-002',
    ticketId: 'TKT-78456',
    itemValue: 45999,
    itemName: 'iPhone 15 Pro Max',
    detectedKeyword: 'Received stones',
    sentimentScore: -0.92,
    transcriptSnippet: '"I am shocked! Instead of my iPhone, there were stones and paper wrapped inside the original packaging..."',
    channel: 'Chat',
    timestamp: '2024-12-05T09:45:00Z',
    riskLevel: 'CRITICAL',
  },
  {
    id: 'EB-003',
    ticketId: 'TKT-78123',
    itemValue: 32499,
    itemName: 'Sony WH-1000XM5',
    detectedKeyword: 'Seal broken',
    sentimentScore: -0.65,
    transcriptSnippet: '"Package seal was clearly tampered with. The box had a Sony headphone case but inside was a cheap Chinese knockoff..."',
    channel: 'Email',
    timestamp: '2024-12-05T08:12:00Z',
    riskLevel: 'HIGH',
  },
  {
    id: 'EB-004',
    ticketId: 'TKT-77998',
    itemValue: 156000,
    itemName: 'Gold Chain 22K',
    detectedKeyword: 'Empty jewelry box',
    sentimentScore: -0.95,
    transcriptSnippet: '"The velvet box was there, the certificate was there, but no gold chain! This is clearly theft during transit..."',
    channel: 'Voice Transcripts',
    timestamp: '2024-12-05T07:30:00Z',
    riskLevel: 'CRITICAL',
  },
  {
    id: 'EB-005',
    ticketId: 'TKT-77856',
    itemValue: 28999,
    itemName: 'Samsung Galaxy S24 Ultra',
    detectedKeyword: 'Received paper',
    sentimentScore: -0.78,
    transcriptSnippet: '"Unboxed on camera and found newspaper cuttings weighted to match phone weight. This is organized fraud..."',
    channel: 'Social Posts',
    timestamp: '2024-12-04T22:15:00Z',
    riskLevel: 'HIGH',
  },
  {
    id: 'EB-006',
    ticketId: 'TKT-77654',
    itemValue: 12999,
    itemName: 'AirPods Pro',
    detectedKeyword: 'Counterfeit swap',
    sentimentScore: -0.71,
    transcriptSnippet: '"These are clearly fake AirPods. The packaging says Apple but the product inside is a cheap replica..."',
    channel: 'Chat',
    timestamp: '2024-12-04T19:45:00Z',
    riskLevel: 'HIGH',
  },
];

// Widget 3: Agent Collusion Watchlist Data
export const agentCollusionData: AgentCollusionRisk[] = [
  {
    id: 'AG-001',
    agentName: 'Rajesh M.',
    agentId: 'EMP-4521',
    collusionRiskScore: 94,
    flaggedPhrase: 'I will override policy',
    outOfPolicyApprovals: 47,
    lastFlaggedAt: '2024-12-05T11:30:00Z',
    department: 'Returns & Refunds',
    transcriptSnippets: [
      '"Don\'t worry, I\'ll make an exception for you this time..."',
      '"Let me approve this without the usual documentation..."',
    ],
    detectedPatterns: ['Policy Override', 'Documentation Bypass', 'VIP Treatment'],
  },
  {
    id: 'AG-002',
    agentName: 'Priya S.',
    agentId: 'EMP-3892',
    collusionRiskScore: 87,
    flaggedPhrase: 'Goodwill refund approved',
    outOfPolicyApprovals: 38,
    lastFlaggedAt: '2024-12-05T10:15:00Z',
    department: 'Customer Support',
    transcriptSnippets: [
      '"I\'ve processed a goodwill gesture, no need for proof..."',
      '"Your account has been credited, forget about the return..."',
    ],
    detectedPatterns: ['Excessive Goodwill', 'No-Return Refunds', 'Credit Abuse'],
  },
  {
    id: 'AG-003',
    agentName: 'Amit K.',
    agentId: 'EMP-5673',
    collusionRiskScore: 78,
    flaggedPhrase: 'Between us only',
    outOfPolicyApprovals: 29,
    lastFlaggedAt: '2024-12-04T16:45:00Z',
    department: 'Escalations',
    transcriptSnippets: [
      '"Keep this between us, I\'m helping you out here..."',
      '"Don\'t mention this conversation to anyone..."',
    ],
    detectedPatterns: ['Secrecy Indicators', 'Off-Record Deals', 'Trust Building'],
  },
  {
    id: 'AG-004',
    agentName: 'Sneha R.',
    agentId: 'EMP-2341',
    collusionRiskScore: 72,
    flaggedPhrase: 'Special case exception',
    outOfPolicyApprovals: 23,
    lastFlaggedAt: '2024-12-04T14:20:00Z',
    department: 'Returns & Refunds',
    transcriptSnippets: [
      '"I\'m marking this as a special case, don\'t worry..."',
      '"Let me bypass the verification for you..."',
    ],
    detectedPatterns: ['Verification Bypass', 'Special Treatment', 'Fast-Track'],
  },
  {
    id: 'AG-005',
    agentName: 'Vikram T.',
    agentId: 'EMP-6789',
    collusionRiskScore: 65,
    flaggedPhrase: 'Manager approval not needed',
    outOfPolicyApprovals: 18,
    lastFlaggedAt: '2024-12-04T11:00:00Z',
    department: 'Customer Support',
    transcriptSnippets: [
      '"I have the authority, no need to escalate..."',
      '"Trust me, I\'ll handle this directly..."',
    ],
    detectedPatterns: ['Authority Abuse', 'Escalation Avoidance', 'Solo Approval'],
  },
];

// Widget 4: Fake Escalation Detector Data
export const escalationData: EscalationData[] = [
  {
    type: 'Legitimate',
    count: 1247,
    percentage: 68.3,
  },
  {
    type: 'Ghost',
    count: 578,
    percentage: 31.7,
  },
];

export const ghostEscalationDetails: GhostEscalationDetail[] = [
  {
    id: 'GE-001',
    ticketId: 'TKT-76543',
    customerSentiment: 0.23,
    escalationReason: 'Customer demanded supervisor',
    actualCustomerTone: 'Calm, polite inquiry',
    flaggedBy: 'NLP Sentiment Analyzer',
    timestamp: '2024-12-05T11:00:00Z',
  },
  {
    id: 'GE-002',
    ticketId: 'TKT-76234',
    customerSentiment: 0.45,
    escalationReason: 'Extreme dissatisfaction',
    actualCustomerTone: 'Neutral, factual complaint',
    flaggedBy: 'Tone Mismatch Detector',
    timestamp: '2024-12-05T09:30:00Z',
  },
  {
    id: 'GE-003',
    ticketId: 'TKT-75987',
    customerSentiment: 0.67,
    escalationReason: 'Threatening legal action',
    actualCustomerTone: 'Friendly, understanding',
    flaggedBy: 'Escalation Pattern Analyzer',
    timestamp: '2024-12-04T17:45:00Z',
  },
];

// Widget 5: Coercion & Social Engineering Data
export const coercionAlerts: CoercionAlert[] = [
  {
    id: 'CE-001',
    type: 'Legal Threat',
    customerId: 'CUST-89234',
    threatLevel: 'CRITICAL',
    detectedPhrase: 'Consumer Forum complaint',
    transcriptSnippet: '"I will file a case in Consumer Forum tomorrow. My lawyer is already preparing the documents. You will pay for harassment..."',
    channel: 'Chat',
    timestamp: '2024-12-05T11:45:00Z',
    platform: 'Consumer Forum',
  },
  {
    id: 'CE-002',
    type: 'Reputation Leverage Attacks',
    customerId: 'CUST-78456',
    threatLevel: 'HIGH',
    detectedPhrase: 'Viral Twitter thread',
    transcriptSnippet: '"I have 50K followers on Twitter. One thread about your fraud and your stock will crash. Refund me NOW or face consequences..."',
    channel: 'Email',
    timestamp: '2024-12-05T10:30:00Z',
    platform: 'Twitter/X',
  },
  {
    id: 'CE-003',
    type: 'Urgency Pressure',
    customerId: 'CUST-67234',
    threatLevel: 'MEDIUM',
    detectedPhrase: 'Flight in 2 hours',
    transcriptSnippet: '"I have a flight to catch in 2 hours! This is for my daughter\'s birthday gift. If you don\'t refund now, her birthday is ruined..."',
    channel: 'Voice Transcripts',
    timestamp: '2024-12-05T09:15:00Z',
    urgencyIndicator: 'Flight to catch',
  },
  {
    id: 'CE-004',
    type: 'Legal Threat',
    customerId: 'CUST-56789',
    threatLevel: 'HIGH',
    detectedPhrase: 'Police complaint filed',
    transcriptSnippet: '"I have already filed an FIR at the cyber cell. Your company name is mentioned. Refund immediately or face arrest..."',
    channel: 'Tickets',
    timestamp: '2024-12-05T08:00:00Z',
    platform: 'Cyber Cell',
  },
  {
    id: 'CE-005',
    type: 'Reputation Leverage Attacks',
    customerId: 'CUST-45123',
    threatLevel: 'CRITICAL',
    detectedPhrase: 'Expose video threat',
    transcriptSnippet: '"My unboxing video showing your fraud has 100K views already. More coming. Give me full refund + compensation or I escalate..."',
    channel: 'Social Posts',
    timestamp: '2024-12-04T22:30:00Z',
    platform: 'Twitter',
  },
  {
    id: 'CE-006',
    type: 'Urgency Pressure',
    customerId: 'CUST-34567',
    threatLevel: 'MEDIUM',
    detectedPhrase: 'Medical emergency',
    transcriptSnippet: '"This is a medical device for my mother who is in ICU. Every minute counts! Process refund immediately, I need to buy from pharmacy..."',
    channel: 'Chat',
    timestamp: '2024-12-04T20:15:00Z',
    urgencyIndicator: 'Medical Emergency',
  },
];

// Widget 6: Promo & Referral Abuse Keywords
export const abuseKeywords: AbuseKeyword[] = [
  {
    keyword: 'Loot deal',
    frequency: 342,
    source: 'Social Posts',
    riskWeight: 5,
    examples: ['"Bro use this code for loot deal, unlimited times works..."', '"This loot deal trick still active, hurry!"'],
    firstDetected: '2024-11-15T00:00:00Z',
    lastDetected: '2024-12-05T10:30:00Z',
  },
  {
    keyword: 'Unlimited trick',
    frequency: 287,
    source: 'Chat',
    riskWeight: 5,
    examples: ['"Unlimited referral trick working, made 5K today..."', '"Create new accounts, unlimited cashback trick"'],
    firstDetected: '2024-11-20T00:00:00Z',
    lastDetected: '2024-12-05T09:45:00Z',
  },
  {
    keyword: 'Referral bypass',
    frequency: 198,
    source: 'Social Posts',
    riskWeight: 4,
    examples: ['"Bypass referral limit using VPN..."', '"New referral bypass method found!"'],
    firstDetected: '2024-11-25T00:00:00Z',
    lastDetected: '2024-12-05T08:20:00Z',
  },
  {
    keyword: 'Refund trick',
    frequency: 256,
    source: 'Chat',
    riskWeight: 5,
    examples: ['"Easy refund trick: claim empty box..."', '"100% refund trick without return"'],
    firstDetected: '2024-11-10T00:00:00Z',
    lastDetected: '2024-12-05T11:00:00Z',
  },
  {
    keyword: 'Fake account farm',
    frequency: 145,
    source: 'Tickets',
    riskWeight: 4,
    examples: ['"Running 50 accounts for referral farming..."', '"Account farm setup guide shared in group"'],
    firstDetected: '2024-11-28T00:00:00Z',
    lastDetected: '2024-12-04T23:30:00Z',
  },
  {
    keyword: 'Coupon stacking',
    frequency: 178,
    source: 'Social Posts',
    riskWeight: 3,
    examples: ['"Stack 3 coupons using this bug..."', '"Coupon stacking glitch discovered!"'],
    firstDetected: '2024-11-22T00:00:00Z',
    lastDetected: '2024-12-05T07:15:00Z',
  },
  {
    keyword: 'Promo code leak',
    frequency: 234,
    source: 'Social Posts',
    riskWeight: 4,
    examples: ['"Internal promo code leaked: SAVE90..."', '"Employee discount code working for all"'],
    firstDetected: '2024-11-18T00:00:00Z',
    lastDetected: '2024-12-05T10:00:00Z',
  },
  {
    keyword: 'Return fraud group',
    frequency: 89,
    source: 'Chat',
    riskWeight: 5,
    examples: ['"Join our Telegram for return fraud tips..."', '"Private group for refund schemes"'],
    firstDetected: '2024-12-01T00:00:00Z',
    lastDetected: '2024-12-05T06:45:00Z',
  },
  {
    keyword: 'Free product hack',
    frequency: 167,
    source: 'Social Posts',
    riskWeight: 4,
    examples: ['"Get any product free with this hack..."', '"100% cashback + keep product trick"'],
    firstDetected: '2024-11-12T00:00:00Z',
    lastDetected: '2024-12-04T21:00:00Z',
  },
  {
    keyword: 'System exploit',
    frequency: 78,
    source: 'Email',
    riskWeight: 5,
    examples: ['"Found pricing exploit, items showing ₹1..."', '"Cart bug gives free shipping always"'],
    firstDetected: '2024-12-02T00:00:00Z',
    lastDetected: '2024-12-05T05:30:00Z',
  },
];

// Dashboard Summary Stats
export const dashboardStats: FraudDashboardStats = {
  totalAlerts: 1847,
  criticalAlerts: 234,
  highRiskAgents: 5,
  activeCoercionCases: 23,
  ghostEscalationRate: 31.7,
  lastUpdated: '2024-12-05T12:00:00Z',
};

