/** Generated from RBI_Obligation_Control_Register.xlsx — Fluid-alone controls. */

export type RegisterControl = {
  theme: string;
  obligationId: string;
  obligation: string;
  regulation: string;
  process: string;
  controlId: string;
  control: string;
  detectionSignal: string;
  adherencePct: number | null;
};

export type ObligationMetSummary = {
  theme: string;
  obligationId: string;
  obligation: string;
  process: string;
  metPct: number;
  fluidAloneControls: number;
};

export type CallReasonRow = {
  reason: string;
  obligationId: string;
  volume: number;
  topSignal: string;
  metPct: number;
};

export const REGISTER_FLUID_ALONE_COUNT = 37;
export const REGISTER_OVERALL_MET_PCT = 80;
export const REGISTER_CONDUCT_RISK_SCORE = 68;

export const FLUID_ALONE_CONTROLS: readonly RegisterControl[] = [
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-001",
    obligation: "Detect & reconcile every complaint expressed in conversation against CMS SR records.",
    regulation: "IO Directions 2026",
    process: "Complaint Capture & Reconciliation",
    controlId: "CTL-001a",
    control: "Complaint phrase detected in conversation",
    detectionSignal: "NLP complaint-intent classifier on transcript",
    adherencePct: 96,
  },
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-001",
    obligation: "Detect & reconcile every complaint expressed in conversation against CMS SR records.",
    regulation: "IO Directions 2026",
    process: "Complaint Capture & Reconciliation",
    controlId: "CTL-001b",
    control: "Complaint severity & grievance type inferred",
    detectionSignal: "Intent + sentiment + product entity extraction",
    adherencePct: 91,
  },
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-001",
    obligation: "Detect & reconcile every complaint expressed in conversation against CMS SR records.",
    regulation: "IO Directions 2026",
    process: "Complaint Capture & Reconciliation",
    controlId: "CTL-001d",
    control: "Missed-complaint (no-SR) flag raised",
    detectionSignal: "Derived: complaint present + no SR match",
    adherencePct: 71,
  },
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-002",
    obligation: "First 90s of every inbound complaint must include acknowledgement, SR offer & escalation route.",
    regulation: "IO Directions 2026",
    process: "Inbound Complaint Handling — First 90 Seconds",
    controlId: "CTL-002a",
    control: "Acknowledgement spoken within first 90 seconds",
    detectionSignal: "Timestamped acknowledgement-phrase detection",
    adherencePct: 64,
  },
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-002",
    obligation: "First 90s of every inbound complaint must include acknowledgement, SR offer & escalation route.",
    regulation: "IO Directions 2026",
    process: "Inbound Complaint Handling — First 90 Seconds",
    controlId: "CTL-002b",
    control: "Service request (SR) offered to customer",
    detectionSignal: "SR-offer phrase detection",
    adherencePct: 58,
  },
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-002",
    obligation: "First 90s of every inbound complaint must include acknowledgement, SR offer & escalation route.",
    regulation: "IO Directions 2026",
    process: "Inbound Complaint Handling — First 90 Seconds",
    controlId: "CTL-002c",
    control: "Escalation route disclosed",
    detectionSignal: "Escalation/nodal-officer mention detection",
    adherencePct: 70,
  },
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-003",
    obligation: "Complaint must be tagged to the correct grievance category.",
    regulation: "IO Directions 2026",
    process: "Complaint Classification",
    controlId: "CTL-003a",
    control: "Grievance category inferred from conversation",
    detectionSignal: "Category classifier on transcript",
    adherencePct: 89,
  },
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-004",
    obligation: "Nodal / escalation contact shared when customer asks for it.",
    regulation: "RBC Directions 2025",
    process: "Escalation Disclosure",
    controlId: "CTL-004a",
    control: "Nodal officer / escalation detail shared on request",
    detectionSignal: "Detect request + detect disclosure response",
    adherencePct: 83,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-005",
    obligation: "Recovery calls shall not threaten, shame, harass, or contact non-borrowers.",
    regulation: "Draft Fair Practice Recovery Framework",
    process: "Outbound Recovery Conduct",
    controlId: "CTL-005a",
    control: "No threat / intimidation language",
    detectionSignal: "Threat-language classifier (multilingual)",
    adherencePct: 82,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-005",
    obligation: "Recovery calls shall not threaten, shame, harass, or contact non-borrowers.",
    regulation: "Draft Fair Practice Recovery Framework",
    process: "Outbound Recovery Conduct",
    controlId: "CTL-005b",
    control: "No public shaming / third-party disclosure of default",
    detectionSignal: "Shaming + third-party-disclosure detection",
    adherencePct: 88,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-005",
    obligation: "Recovery calls shall not threaten, shame, harass, or contact non-borrowers.",
    regulation: "Draft Fair Practice Recovery Framework",
    process: "Outbound Recovery Conduct",
    controlId: "CTL-005c",
    control: "No profanity / abusive language",
    detectionSignal: "Profanity classifier (multilingual)",
    adherencePct: 95,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-006",
    obligation: "Recovery contact only within permitted hours (08:00–19:00).",
    regulation: "Fair Practices Code",
    process: "Recovery Call Timing",
    controlId: "CTL-006a",
    control: "Call placed within permitted window",
    detectionSignal: "Call-start timestamp vs permitted window",
    adherencePct: 97,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-007",
    obligation: "Recovery agent must identify self, bank & purpose at call open.",
    regulation: "Fair Practices Code",
    process: "Recovery Call Opening",
    controlId: "CTL-007a",
    control: "Agent identifies self + bank",
    detectionSignal: "Opening-identification phrase detection",
    adherencePct: 90,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-007",
    obligation: "Recovery agent must identify self, bank & purpose at call open.",
    regulation: "Fair Practices Code",
    process: "Recovery Call Opening",
    controlId: "CTL-007b",
    control: "Purpose & outstanding amount stated",
    detectionSignal: "Purpose-statement detection",
    adherencePct: 86,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-008",
    obligation: "Engage hardship pathway when borrower-distress markers are detected.",
    regulation: "Draft Fair Practice Recovery Framework",
    process: "Borrower Distress Handling",
    controlId: "CTL-008a",
    control: "Distress cue detected (job loss, illness, bereavement)",
    detectionSignal: "Distress-marker classifier",
    adherencePct: 86,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-008",
    obligation: "Engage hardship pathway when borrower-distress markers are detected.",
    regulation: "Draft Fair Practice Recovery Framework",
    process: "Borrower Distress Handling",
    controlId: "CTL-008b",
    control: "Hardship pathway offered after distress cue",
    detectionSignal: "Hardship-offer detection conditional on cue",
    adherencePct: 61,
  },
  {
    theme: "03 · Vulnerable Customer Care",
    obligationId: "OBL-011",
    obligation: "Bereaved customers shall be handled with empathy & routed to specialist desk.",
    regulation: "RBC Directions 2025",
    process: "Vulnerable Routing — Bereavement",
    controlId: "CTL-011a",
    control: "Bereavement cue detected",
    detectionSignal: "Bereavement-marker classifier",
    adherencePct: 90,
  },
  {
    theme: "03 · Vulnerable Customer Care",
    obligationId: "OBL-011",
    obligation: "Bereaved customers shall be handled with empathy & routed to specialist desk.",
    regulation: "RBC Directions 2025",
    process: "Vulnerable Routing — Bereavement",
    controlId: "CTL-011b",
    control: "Empathy language present in response",
    detectionSignal: "Empathy-scoring on agent turns",
    adherencePct: 62,
  },
  {
    theme: "03 · Vulnerable Customer Care",
    obligationId: "OBL-012",
    obligation: "Fraud-victim distress handled with priority & empathy.",
    regulation: "RBC Directions 2025",
    process: "Fraud-Victim Handling",
    controlId: "CTL-012a",
    control: "Fraud-victim cue detected",
    detectionSignal: "Fraud-victim marker classifier",
    adherencePct: 84,
  },
  {
    theme: "03 · Vulnerable Customer Care",
    obligationId: "OBL-012",
    obligation: "Fraud-victim distress handled with priority & empathy.",
    regulation: "RBC Directions 2025",
    process: "Fraud-Victim Handling",
    controlId: "CTL-012b",
    control: "Priority-action + empathy language present",
    detectionSignal: "Empathy + action-commitment detection",
    adherencePct: 66,
  },
  {
    theme: "03 · Vulnerable Customer Care",
    obligationId: "OBL-027",
    obligation: "Vulnerable customers shall not be left on general queue after detection.",
    regulation: "IO Directions 2026",
    process: "Vulnerable Routing — General Queue",
    controlId: "CTL-027a",
    control: "Vulnerable signal detected on general queue",
    detectionSignal: "Vulnerability classifier on general-queue calls",
    adherencePct: 88,
  },
  {
    theme: "04 · Cross-Sell & Bundling Pressure",
    obligationId: "OBL-016",
    obligation: "Suitability / needs stated before product pitch.",
    regulation: "RBC Directions 2025",
    process: "Suitability Disclosure",
    controlId: "CTL-016a",
    control: "Needs / suitability check verbalised before pitch",
    detectionSignal: "Suitability-language detection ordered before pitch",
    adherencePct: 73,
  },
  {
    theme: "04 · Cross-Sell & Bundling Pressure",
    obligationId: "OBL-018",
    obligation: "Cross-sell shall not extract consent under pressure or mandate bundled products.",
    regulation: "RBC Directions 2025",
    process: "Cross-Sell Conduct",
    controlId: "CTL-018a",
    control: "No 'compulsory / mandatory' bundling phrasing",
    detectionSignal: "Compulsory-bundling phrase detection",
    adherencePct: 74,
  },
  {
    theme: "04 · Cross-Sell & Bundling Pressure",
    obligationId: "OBL-018",
    obligation: "Cross-sell shall not extract consent under pressure or mandate bundled products.",
    regulation: "RBC Directions 2025",
    process: "Cross-Sell Conduct",
    controlId: "CTL-018b",
    control: "Consent freely given (no pressure script)",
    detectionSignal: "Pressure-script + consent-coercion detection",
    adherencePct: 80,
  },
  {
    theme: "04 · Cross-Sell & Bundling Pressure",
    obligationId: "OBL-018",
    obligation: "Cross-sell shall not extract consent under pressure or mandate bundled products.",
    regulation: "RBC Directions 2025",
    process: "Cross-Sell Conduct",
    controlId: "CTL-018c",
    control: "Optional-product right-to-decline disclosed",
    detectionSignal: "'You can decline' disclosure detection",
    adherencePct: 69,
  },
  {
    theme: "05 · Vendor BPO Governance",
    obligationId: "OBL-024",
    obligation: "Vendor BPO conduct parity vs in-house — 100% interaction coverage required.",
    regulation: "Outsourcing of IT & Recovery Directions",
    process: "Vendor Conduct Oversight",
    controlId: "CTL-024a",
    control: "100% interaction coverage achieved (vs legacy sample)",
    detectionSignal: "Coverage counter on vendor recording stream",
    adherencePct: 100,
  },
  {
    theme: "05 · Vendor BPO Governance",
    obligationId: "OBL-024",
    obligation: "Vendor BPO conduct parity vs in-house — 100% interaction coverage required.",
    regulation: "Outsourcing of IT & Recovery Directions",
    process: "Vendor Conduct Oversight",
    controlId: "CTL-024b",
    control: "Conduct parity vs in-house benchmark",
    detectionSignal: "Comparative conduct scoring vendor vs in-house",
    adherencePct: 68,
  },
  {
    theme: "05 · Vendor BPO Governance",
    obligationId: "OBL-025",
    obligation: "Vendor agents follow approved bank script & standards.",
    regulation: "Outsourcing of IT & Recovery Directions",
    process: "Vendor Script Adherence",
    controlId: "CTL-025a",
    control: "Script adherence scored on vendor calls",
    detectionSignal: "Script-match scoring on transcript",
    adherencePct: 72,
  },
  {
    theme: "06 · Repeat-Contact & FCR",
    obligationId: "OBL-030",
    obligation: "Repeat-contact same-customer same-issue must trigger FCR root-cause review.",
    regulation: "IO Directions 2026",
    process: "Repeat-Contact / FCR",
    controlId: "CTL-030a",
    control: "Repeat-contact cluster flagged (same issue, 14d)",
    detectionSignal: "Conversation linking across contacts",
    adherencePct: 84,
  },
  {
    theme: "06 · Repeat-Contact & FCR",
    obligationId: "OBL-031",
    obligation: "Unresolved-on-first-contact must be detected.",
    regulation: "IO Directions 2026",
    process: "First Contact Resolution",
    controlId: "CTL-031a",
    control: "Resolution-failure cue detected at close",
    detectionSignal: "Unresolved-intent detection at call close",
    adherencePct: 78,
  },
  {
    theme: "07 · Disclosure-in-Conversation",
    obligationId: "OBL-014",
    obligation: "Key Fact Statement (KFS) shall be read out during loan / credit-card sales.",
    regulation: "RBC Directions 2025",
    process: "Sales Disclosure — KFS",
    controlId: "CTL-014a",
    control: "KFS read-out detected in conversation",
    detectionSignal: "KFS-script detection on sales calls",
    adherencePct: 67,
  },
  {
    theme: "07 · Disclosure-in-Conversation",
    obligationId: "OBL-015",
    obligation: "Cooling-off / free-look period mentioned at point of sale.",
    regulation: "RBC Directions 2025",
    process: "Cooling-off Disclosure",
    controlId: "CTL-015a",
    control: "Cooling-off / free-look period mentioned",
    detectionSignal: "Cooling-off phrase detection",
    adherencePct: 75,
  },
  {
    theme: "07 · Disclosure-in-Conversation",
    obligationId: "OBL-017",
    obligation: "Pre-payment / foreclosure terms disclosed when asked.",
    regulation: "Fair Practices Code",
    process: "Pre-payment Disclosure",
    controlId: "CTL-017a",
    control: "Foreclosure / pre-payment terms stated on request",
    detectionSignal: "Detect request + disclosure response",
    adherencePct: 81,
  },
  {
    theme: "07 · Disclosure-in-Conversation",
    obligationId: "OBL-019",
    obligation: "Penal charges shall not be phrased as 'penal interest'.",
    regulation: "RBC Directions 2025",
    process: "Charge Communication",
    controlId: "CTL-019a",
    control: "Banned-phrase 'penal interest' occurrences",
    detectionSignal: "Banned-phrase detection",
    adherencePct: 93,
  },
  {
    theme: "08 · Language & Campaign Conduct",
    obligationId: "OBL-028",
    obligation: "Customer offered service in preferred / regional language.",
    regulation: "RBC Directions 2025",
    process: "Language Offer",
    controlId: "CTL-028a",
    control: "Preferred-language offer made",
    detectionSignal: "Language-offer phrase detection",
    adherencePct: 79,
  },
  {
    theme: "08 · Language & Campaign Conduct",
    obligationId: "OBL-029",
    obligation: "Language-mismatch (regional customer → English-only agent) shall trigger re-routing.",
    regulation: "IO Directions 2026",
    process: "Language Routing",
    controlId: "CTL-029a",
    control: "Language mismatch detected",
    detectionSignal: "Customer-language vs agent-language detection",
    adherencePct: 76,
  },
  {
    theme: "08 · Language & Campaign Conduct",
    obligationId: "OBL-026",
    obligation: "Campaign script-deviation must be detected.",
    regulation: "RBC Directions 2025",
    process: "Campaign Adherence",
    controlId: "CTL-026a",
    control: "Script deviation flagged on campaign calls",
    detectionSignal: "Script-match deviation scoring",
    adherencePct: 70,
  },
];

export const OBLIGATION_MET_SUMMARIES: readonly ObligationMetSummary[] = [
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-001",
    obligation: "Detect & reconcile every complaint expressed in conversation against CMS SR records.",
    process: "Complaint Capture & Reconciliation",
    metPct: 86,
    fluidAloneControls: 3,
  },
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-002",
    obligation: "First 90s of every inbound complaint must include acknowledgement, SR offer & escalation route.",
    process: "Inbound Complaint Handling — First 90 Seconds",
    metPct: 64,
    fluidAloneControls: 3,
  },
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-003",
    obligation: "Complaint must be tagged to the correct grievance category.",
    process: "Complaint Classification",
    metPct: 89,
    fluidAloneControls: 1,
  },
  {
    theme: "01 · Complaint Capture & First-90s",
    obligationId: "OBL-004",
    obligation: "Nodal / escalation contact shared when customer asks for it.",
    process: "Escalation Disclosure",
    metPct: 83,
    fluidAloneControls: 1,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-005",
    obligation: "Recovery calls shall not threaten, shame, harass, or contact non-borrowers.",
    process: "Outbound Recovery Conduct",
    metPct: 88,
    fluidAloneControls: 3,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-006",
    obligation: "Recovery contact only within permitted hours (08:00–19:00).",
    process: "Recovery Call Timing",
    metPct: 97,
    fluidAloneControls: 1,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-007",
    obligation: "Recovery agent must identify self, bank & purpose at call open.",
    process: "Recovery Call Opening",
    metPct: 88,
    fluidAloneControls: 2,
  },
  {
    theme: "02 · Recovery Conduct",
    obligationId: "OBL-008",
    obligation: "Engage hardship pathway when borrower-distress markers are detected.",
    process: "Borrower Distress Handling",
    metPct: 74,
    fluidAloneControls: 2,
  },
  {
    theme: "03 · Vulnerable Customer Care",
    obligationId: "OBL-011",
    obligation: "Bereaved customers shall be handled with empathy & routed to specialist desk.",
    process: "Vulnerable Routing — Bereavement",
    metPct: 76,
    fluidAloneControls: 2,
  },
  {
    theme: "03 · Vulnerable Customer Care",
    obligationId: "OBL-012",
    obligation: "Fraud-victim distress handled with priority & empathy.",
    process: "Fraud-Victim Handling",
    metPct: 75,
    fluidAloneControls: 2,
  },
  {
    theme: "07 · Disclosure-in-Conversation",
    obligationId: "OBL-014",
    obligation: "Key Fact Statement (KFS) shall be read out during loan / credit-card sales.",
    process: "Sales Disclosure — KFS",
    metPct: 67,
    fluidAloneControls: 1,
  },
  {
    theme: "07 · Disclosure-in-Conversation",
    obligationId: "OBL-015",
    obligation: "Cooling-off / free-look period mentioned at point of sale.",
    process: "Cooling-off Disclosure",
    metPct: 75,
    fluidAloneControls: 1,
  },
  {
    theme: "04 · Cross-Sell & Bundling Pressure",
    obligationId: "OBL-016",
    obligation: "Suitability / needs stated before product pitch.",
    process: "Suitability Disclosure",
    metPct: 73,
    fluidAloneControls: 1,
  },
  {
    theme: "07 · Disclosure-in-Conversation",
    obligationId: "OBL-017",
    obligation: "Pre-payment / foreclosure terms disclosed when asked.",
    process: "Pre-payment Disclosure",
    metPct: 81,
    fluidAloneControls: 1,
  },
  {
    theme: "04 · Cross-Sell & Bundling Pressure",
    obligationId: "OBL-018",
    obligation: "Cross-sell shall not extract consent under pressure or mandate bundled products.",
    process: "Cross-Sell Conduct",
    metPct: 74,
    fluidAloneControls: 3,
  },
  {
    theme: "07 · Disclosure-in-Conversation",
    obligationId: "OBL-019",
    obligation: "Penal charges shall not be phrased as 'penal interest'.",
    process: "Charge Communication",
    metPct: 93,
    fluidAloneControls: 1,
  },
  {
    theme: "05 · Vendor BPO Governance",
    obligationId: "OBL-024",
    obligation: "Vendor BPO conduct parity vs in-house — 100% interaction coverage required.",
    process: "Vendor Conduct Oversight",
    metPct: 84,
    fluidAloneControls: 2,
  },
  {
    theme: "05 · Vendor BPO Governance",
    obligationId: "OBL-025",
    obligation: "Vendor agents follow approved bank script & standards.",
    process: "Vendor Script Adherence",
    metPct: 72,
    fluidAloneControls: 1,
  },
  {
    theme: "08 · Language & Campaign Conduct",
    obligationId: "OBL-026",
    obligation: "Campaign script-deviation must be detected.",
    process: "Campaign Adherence",
    metPct: 70,
    fluidAloneControls: 1,
  },
  {
    theme: "03 · Vulnerable Customer Care",
    obligationId: "OBL-027",
    obligation: "Vulnerable customers shall not be left on general queue after detection.",
    process: "Vulnerable Routing — General Queue",
    metPct: 88,
    fluidAloneControls: 1,
  },
  {
    theme: "08 · Language & Campaign Conduct",
    obligationId: "OBL-028",
    obligation: "Customer offered service in preferred / regional language.",
    process: "Language Offer",
    metPct: 79,
    fluidAloneControls: 1,
  },
  {
    theme: "08 · Language & Campaign Conduct",
    obligationId: "OBL-029",
    obligation: "Language-mismatch (regional customer → English-only agent) shall trigger re-routing.",
    process: "Language Routing",
    metPct: 76,
    fluidAloneControls: 1,
  },
  {
    theme: "06 · Repeat-Contact & FCR",
    obligationId: "OBL-030",
    obligation: "Repeat-contact same-customer same-issue must trigger FCR root-cause review.",
    process: "Repeat-Contact / FCR",
    metPct: 84,
    fluidAloneControls: 1,
  },
  {
    theme: "06 · Repeat-Contact & FCR",
    obligationId: "OBL-031",
    obligation: "Unresolved-on-first-contact must be detected.",
    process: "First Contact Resolution",
    metPct: 78,
    fluidAloneControls: 1,
  },
];

export const OBLIGATION_MET_BY_ID: Record<string, ObligationMetSummary> =
  Object.fromEntries(OBLIGATION_MET_SUMMARIES.map((o) => [o.obligationId, o]));

export const TOP_CALL_REASONS: readonly CallReasonRow[] = [
  {
    reason: "ECS / charge dispute",
    obligationId: "OBL-001",
    volume: 1842,
    topSignal: "Complaint not logged to CMS",
    metPct: 71,
  },
  {
    reason: "Loan EMI bounce / recovery",
    obligationId: "OBL-005",
    volume: 1264,
    topSignal: "Threat or shaming language",
    metPct: 82,
  },
  {
    reason: "Credit card fee waiver",
    obligationId: "OBL-002",
    volume: 988,
    topSignal: "No SR offer in first 90s",
    metPct: 64,
  },
  {
    reason: "ULIP / bundling on salary a/c",
    obligationId: "OBL-018",
    volume: 742,
    topSignal: "Mandatory bundling phrasing",
    metPct: 74,
  },
  {
    reason: "Fraud / unauthorized txn",
    obligationId: "OBL-012",
    volume: 618,
    topSignal: "Low empathy on fraud-victim queue",
    metPct: 66,
  },
  {
    reason: "Language mismatch routing",
    obligationId: "OBL-029",
    volume: 412,
    topSignal: "Regional customer to English agent",
    metPct: 76,
  },
  {
    reason: "KFS not read on PL sale",
    obligationId: "OBL-014",
    volume: 284,
    topSignal: "KFS read-out missing",
    metPct: 67,
  },
  {
    reason: "Repeat same-issue contact",
    obligationId: "OBL-030",
    volume: 1964,
    topSignal: "FCR failure within 14 days",
    metPct: 84,
  },
];

export const VIOLATION_TREND_WEEKLY = [
  { week: "W1", violations: 42, breaches: 34 },
  { week: "W2", violations: 38, breaches: 30 },
  { week: "W3", violations: 51, breaches: 43 },
  { week: "W4", violations: 47, breaches: 39 },
  { week: "W5", violations: 44, breaches: 36 },
  { week: "W6", violations: 39, breaches: 31 },
  { week: "W7", violations: 35, breaches: 28 },
] as const;
