import type { FCICluster } from "@/lib/fci-lib/fciData";

/** Flipkart e-commerce failure clusters for What's Failing? wall */
export const FLIPKART_FCI_CLUSTERS: FCICluster[] = [
  {
    id: "fk-1",
    category: "Payment & UPI checkout",
    count: 2840,
    trend: 14.2,
    severity: "High Impact",
    examples: [
      "UPI deducted but order stuck on confirming — app review",
      "COD unavailable after cart built at checkout",
      "Card decline on ₹42K electronics cart at peak hour",
      "Payment retry loop on Flipkart Pay",
    ],
    affectedCustomers: 2140,
    businessImpact: "Cart abandonment, GMV loss during BBD peak, Plus churn risk",
    totalInteractions: 8420,
    avgResolutionTime: "1.8 hours",
    topChannels: [
      { channel: "Voice", percentage: 42 },
      { channel: "Chat", percentage: 29 },
      { channel: "Social Media", percentage: 11 },
      { channel: "Email", percentage: 10 },
      { channel: "Ticket", percentage: 8 },
    ],
    topics: ["UPI failure", "Checkout step", "COD block", "Flipkart Pay", "Card decline"],
    nextActionSuggestion: "Route to Payments — gateway patch + in-app retry UX before evening sale load",
    processError: 68,
    productKnowledgeGap: 32,
  },
  {
    id: "fk-2",
    category: "Order not received",
    count: 2210,
    trend: 18.6,
    severity: "High Impact",
    examples: [
      "Marked delivered — nothing at door (#NeverDelivered)",
      "Fake delivery OTP accepted by courier",
      "Locker pickup code never received",
      "Gift order missing — recipient escalated on social",
    ],
    affectedCustomers: 1890,
    businessImpact: "#NeverDelivered viral risk, trust erosion vs Amazon, repeat contact surge",
    totalInteractions: 6840,
    avgResolutionTime: "4.2 hours",
    topChannels: [
      { channel: "Voice", percentage: 44 },
      { channel: "Chat", percentage: 24 },
      { channel: "Social Media", percentage: 11 },
      { channel: "Email", percentage: 13 },
      { channel: "Ticket", percentage: 8 },
    ],
    topics: ["#NeverDelivered", "Fake delivery", "Locker", "Last-mile", "OTP dispute"],
    nextActionSuggestion: "WH-East audit + courier SLA escalation for pin codes flagged on social",
    processError: 55,
    productKnowledgeGap: 45,
  },
  {
    id: "fk-3",
    category: "Refund & return delays",
    count: 1980,
    trend: 11.3,
    severity: "High Impact",
    examples: [
      "UPI refund pending >72h with no status update",
      "Return pickup scheduled — nobody came",
      "Exchange stuck after wrong-SKU delivery",
      "Wallet credit not reflecting after approved return",
    ],
    affectedCustomers: 1640,
    businessImpact: "Refund SLA gap vs Amazon, repeat contacts, negative app-store reviews",
    totalInteractions: 5920,
    avgResolutionTime: "3.6 hours",
    topChannels: [
      { channel: "Chat", percentage: 31 },
      { channel: "Voice", percentage: 36 },
      { channel: "Email", percentage: 14 },
      { channel: "Social Media", percentage: 9 },
      { channel: "Ticket", percentage: 10 },
    ],
    topics: ["UPI refund", "Return pickup", "Exchange", "Wallet credit", "SLA breach"],
    nextActionSuggestion: "Auto SMS on refund initiation + pickup reschedule for open >48h cases",
    processError: 62,
    productKnowledgeGap: 38,
  },
  {
    id: "fk-4",
    category: "Delivery delay & SLA",
    count: 1620,
    trend: 9.8,
    severity: "High Impact",
    examples: [
      "Express slot missed during Big Billion Days",
      "ETA changed three times — order still in hub",
      "Tier-2 city delay vs promised 2-day delivery",
      "Rain-delay backlog in Bengaluru hubs",
    ],
    affectedCustomers: 1380,
    businessImpact: "Plus promise breach, festival-season NPS dip, competitor switch intent",
    totalInteractions: 4860,
    avgResolutionTime: "2.4 hours",
    topChannels: [
      { channel: "Chat", percentage: 30 },
      { channel: "Voice", percentage: 36 },
      { channel: "Social Media", percentage: 13 },
      { channel: "Email", percentage: 12 },
      { channel: "Ticket", percentage: 9 },
    ],
    topics: ["Express SLA", "BBD backlog", "Hub delay", "ETA slip", "Plus delivery"],
    nextActionSuggestion: "Capacity plan WH-East + proactive delay comms before slot breach",
    processError: 58,
    productKnowledgeGap: 42,
  },
  {
    id: "fk-5",
    category: "Wrong item & damaged goods",
    count: 1240,
    trend: 6.4,
    severity: "Medium",
    examples: [
      "Used phone received on premium electronics listing",
      "Empty box delivery before festival sale",
      "Damaged appliance — photo evidence in review",
      "Wrong colour fashion SKU vs product page",
    ],
    affectedCustomers: 980,
    businessImpact: "Quality trust break, return logistics cost, seller scorecard hits",
    totalInteractions: 3720,
    avgResolutionTime: "3.1 hours",
    topChannels: [
      { channel: "Chat", percentage: 31 },
      { channel: "Voice", percentage: 34 },
      { channel: "Social Media", percentage: 11 },
      { channel: "Email", percentage: 18 },
      { channel: "Ticket", percentage: 6 },
    ],
    topics: ["Wrong SKU", "Damaged", "Empty box", "Used product", "Quality"],
    nextActionSuggestion: "Seller watchdog sweep on electronics ahead of BBD listings",
    processError: 48,
    productKnowledgeGap: 52,
  },
  {
    id: "fk-6",
    category: "Seller trust & listings",
    count: 720,
    trend: 8.1,
    severity: "Medium",
    examples: [
      "Counterfeit suspected on branded electronics",
      "Seller ghosting after wrong-SKU photo thread",
      "MRP mismatch vs cart on third-party seller",
      "Fake reviews flagged on viral X thread",
    ],
    affectedCustomers: 610,
    businessImpact: "Brand risk on marketplace trust, returns spike on high-GMV SKUs",
    totalInteractions: 2160,
    avgResolutionTime: "2.8 hours",
    topChannels: [
      { channel: "Social Media", percentage: 26 },
      { channel: "Chat", percentage: 25 },
      { channel: "Voice", percentage: 29 },
      { channel: "Email", percentage: 12 },
      { channel: "Ticket", percentage: 8 },
    ],
    topics: ["Counterfeit", "Seller fraud", "Listing quality", "MRP mismatch", "Reviews"],
    nextActionSuggestion: "Trust & safety queue for sellers flagged in #NeverDelivered threads",
    processError: 40,
    productKnowledgeGap: 60,
  },
  {
    id: "fk-7",
    category: "Platform fee & promos",
    count: 540,
    trend: 12.0,
    severity: "Medium",
    examples: [
      "Hidden fee shock at checkout vs cart total",
      "SuperCoins not applied after promised offer",
      "BBD coupon rejected at payment step",
      "Meesho comparison on zero-fee checkout posts",
    ],
    affectedCustomers: 480,
    businessImpact: "Checkout abandonment, social comparison vs Amazon / Meesho",
    totalInteractions: 1620,
    avgResolutionTime: "1.5 hours",
    topChannels: [
      { channel: "Social Media", percentage: 22 },
      { channel: "Chat", percentage: 28 },
      { channel: "Voice", percentage: 32 },
      { channel: "Email", percentage: 10 },
      { channel: "Ticket", percentage: 8 },
    ],
    topics: ["Platform fee", "SuperCoins", "Coupon", "Checkout total", "Promo"],
    nextActionSuggestion: "In-app fee breakdown at checkout + SuperCoins status line item",
    processError: 72,
    productKnowledgeGap: 28,
  },
];
