"""Card G (app release) candidate: compute the trigger from the public voice and write docs/indusind/card_g_candidate.md.

IND-B4 makes G a conditional card that replaces a tile when its trigger fires, but gives no numeric trigger. The one
used here (IndusInd V1, IV-38) fires for a week when all three hold, on Google Play INDIE reviews:
  1. at least `min_items` (15) reviews in the week carry the "App blocked as a security risk" theme;
  2. the theme is at least 10% of the week's app reviews;
  3. it is concentrated on new releases: its share on the newest versions is at least 5× its share on the previous
     stable version.
The card is NOT swapped in: that is Ranjith's call. This file only says what it would show.
"""

from __future__ import annotations

import collections
import sys

import indusind_l2_metrics as M

OUT = M.ROOT / "docs" / "indusind" / "card_g_candidate.md"
STABLE = "2.3.1"
NEW = ("2.5.0", "2.6.0")
SHARE_MIN, RATIO_MIN = 10.0, 5.0


def pct(n, d):
    return round(100 * n / d, 1) if d else 0.0


def main() -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    items = M.load()
    play = [i for i in items if i["source"] == "play" and i["product"] == "app_digital"]
    weeks = sorted({i["week_end"] for i in play})
    rows, fired = [], []
    for w in weeks:
        xs = [i for i in play if i["week_end"] == w]
        sb = [i for i in xs if i["theme"] == "security_block"]
        lo = [i for i in xs if i["theme"] == "login_otp"]
        new = [i for i in xs if i["app_version"] in NEW]
        old = [i for i in xs if i["app_version"] == STABLE]
        s_new = pct(sum(i["theme"] == "security_block" for i in new), len(new))
        s_old = pct(sum(i["theme"] == "security_block" for i in old), len(old))
        ratio = s_new / s_old if s_old else (float("inf") if s_new else 0.0)
        on = len(sb) >= M.L2C["min_items"] and pct(len(sb), len(xs)) >= SHARE_MIN and ratio >= RATIO_MIN
        if on:
            fired.append(w)
        rows.append((w, len(xs), len(sb), pct(len(sb), len(xs)), s_new, s_old, len(lo), "fires" if on else "—"))
    by_version = collections.defaultdict(lambda: [0, 0, 0])
    for i in play:
        v = by_version[i["app_version"]]
        v[0] += 1
        v[1] += i["theme"] == "security_block"
        v[2] += i["theme"] == "login_otp"
    rating = M.listing()
    last = rows[-1]
    md = [
        "# Card G candidate · App release (not swapped in)",
        "",
        "**Status: candidate only.** IND-B4 says conditional card G replaces a home tile when its trigger fires. "
        "Whether it does is Ranjith's call; the home page still shows cards A–D. Generated by "
        "`scripts/card_g_candidate.py` from the public voice (INDIE on Google Play, core licence only).",
        "",
        "## Trigger",
        "",
        "IND-B4 gives no numeric trigger. The one used here fires for a week when all three hold:",
        "",
        f"1. at least {M.L2C['min_items']} reviews in the week carry the \"App blocked as a security risk\" theme;",
        f"2. the theme is at least {SHARE_MIN:.0f}% of the week's app reviews;",
        f"3. its share on the newest releases ({', '.join(NEW)}) is at least {RATIO_MIN:.0f}× its share on the previous "
        f"stable release ({STABLE}).",
        "",
        f"**Result:** the trigger fired in {len(fired)} weeks ({', '.join(fired) or 'none'}). In the week to the "
        f"freeze ({last[0]}) it is **{'firing' if last[-1] == 'fires' else 'not firing'}**: {last[2]} items, "
        f"{last[3]}% of the week's app reviews.",
        "",
        "| Week to | App reviews | Security-block items | Share | Share on new releases | Share on 2.3.1 | Login and OTP items | Trigger |",
        "|---|---|---|---|---|---|---|---|",
        *[f"| {r[0]} | {r[1]:,} | {r[2]} | {r[3]}% | {r[4]}% | {r[5]}% | {r[6]} | {r[7]} |" for r in rows],
        "",
        "Weeks start at 10 Aug, the first Google Play review in the pull (the collector's cap).",
        "",
        "## By app version (10 Aug to 30 Sep)",
        "",
        "| Version | App reviews | Security-block items | Share | Login and OTP items |",
        "|---|---|---|---|---|",
        *[f"| {v} | {n:,} | {sb} | {pct(sb, n)}% | {lo} |" for v, (n, sb, lo) in
          sorted(by_version.items(), key=lambda kv: -kv[1][0]) if n >= 15],
        "",
        "## What the card would show",
        "",
        "- **Title:** \"App release 2.5.0: about one review in five says the app blocks the phone as unsafe\" "
        "(the share at its peak weeks; the live title would bind the week's figure to its L2 id).",
        "- **What moved:** the weekly share of app reviews with the security-block theme, by release, from 10 Aug; "
        f"release {STABLE} stays near 1–3% throughout.",
        "- **Themes by app version:** security block (\"threat detected\", \"use a secure operating system\", "
        "\"screen reader\"), login and OTP or SIM-binding failures; KYC items are too few to show.",
        "- **Listing rating:** " + (f"INDIE listing rating, all-time, as of {rating['as_of']}: {rating['score']} from "
                                    f"{M.fmt_int(rating['ratings'])} ratings (Google Play). Shown apart from the "
                                    "week's figures." if rating else "not available."),
        "- **Peer:** greyed \"pending verification\" (no peer app reviews in the pull).",
        "- **Voice:** paraphrased only; Play replies are near-universal, so \"bank replied\" is not a differentiator.",
        "- **Owner:** Head of Digital Banking (role), with the CIO and customer service.",
        "- **Drafted action:** review the device-integrity rules shipped in 2.5.0 against the phones and settings "
        "customers name (Android 16, HyperOS, screen-reader and accessibility services, developer options), publish a "
        "workaround in the store reply, and track the weekly share back under 3% before the next release. Approver: "
        "Head of Digital Banking.",
        "- **Not on the card:** any count of affected customers (reviews are not incidence), any claim about cause "
        "beyond what reviewers report, and any figure blended across stores.",
        "",
    ]
    OUT.write_text("\n".join(md), encoding="utf-8", newline="\n")
    print(f"card_g_candidate: trigger fired in {len(fired)} weeks ({', '.join(fired)}); week to {last[0]}: {last[-1]}; "
          f"written {OUT.relative_to(M.ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
