import type { DrillRouteKind, ScreenId } from "./routes";
import type {
  AppState,
  AuditEntry,
  EvidencePack,
  SignatureType,
  Signal,
} from "../state/appState";

export interface CategorySignalView extends Signal {
  title: string;
  cohort: string;
  onset: string;
  stats: string;
  aiVerdict: string;
  impactRupee: string;
  screenId: ScreenId;
  drillKind: DrillRouteKind;
  suppressed?: boolean;
  advisory?: boolean;
  integrationDependent?: boolean;
  regimeBadge?: string;
}

export const DEFAULT_RAIL_ORDER = [
  "T2-02",
  "T2-26",
  "T2-28",
  "T2-12",
  "T2-19",
  "T2-07",
  "T2-15",
  "T2-17",
  "SUPPRESSED-TEE",
  "ADVISORY-LANE",
];

const SIGNALS: CategorySignalView[] = [
  {
    signalId: "T2-02",
    cardId: "T2-02",
    title: "Recoverable margin on the Aura shirt run",
    severity: "S1",
    behaviourType: "recoverable-returns",
    cohortId: "SKU-AURA-SHIRT × SELL-TF",
    cohort: "SKU-AURA-SHIRT × SELL-TF",
    baselineCellId: "fashion-returns",
    deviationStat: "31% vs 22% band",
    onsetTs: "Tue 09:40",
    onset: "Tue 09:40",
    causeClass: "RC-SIZE",
    confidence: "High",
    impactValue: "₹6.0L",
    impactRupee: "₹6.0L recoverable",
    ruledOut: ["buyer-remorse majority"],
    honestyLine: "Detection: return rate · Verdict: return free-text + reviews",
    ownerPersona: "Catalogue/PIM",
    signatureType: "A",
    stats: "31% returns vs 22% band · 1,860/6,000 · 64% buyer-intent held out · ~600 fixable units",
    aiVerdict: "Fixable sizing error — chest chart understated; ₹6.0L recoverable if corrected.",
    screenId: "returns-margin",
    drillKind: "returns",
    integrationDependent: true,
    actions: [
      { actionLabel: "Draft", routedOwner: "Catalogue/PIM", gated: false, status: "draft" },
      { actionLabel: "Route", routedOwner: "Seller-Brand", gated: false, status: "draft" },
    ],
  },
  {
    signalId: "T2-26",
    cardId: "T2-26",
    title: "Delhi-NCR lane RTO 33% vs 21%",
    severity: "S1",
    behaviourType: "lane-rto",
    cohortId: "LANE-DEL-NCR-O",
    cohort: "LANE-DEL-NCR-O",
    baselineCellId: "lane-ncr",
    deviationStat: "+12 pts vs band",
    onsetTs: "Mon 14:20",
    onset: "Mon 14:20",
    causeClass: "logistics",
    confidence: "High",
    impactValue: "₹4.2L",
    impactRupee: "₹4.2L lane contribution at risk",
    ruledOut: ["seller quality primary"],
    honestyLine: "Detection: RTO rate · Verdict: lane voice cohort (delivery-theme 70%)",
    ownerPersona: "Operations",
    signatureType: "D",
    stats: "70% delivery-theme voice → logistics (seller penalty held)",
    aiVerdict: "Route to Operations — rider non-attempt / marked undelivered clusters dominate.",
    screenId: "lane-rto",
    drillKind: "lanes",
    actions: [
      { actionLabel: "Route", routedOwner: "Operations", gated: false, status: "draft" },
      { actionLabel: "Route", routedOwner: "Warehouse map (pick/pack gap)", gated: true, status: "draft" },
    ],
  },
  {
    signalId: "T2-28",
    cardId: "T2-28",
    title: "Pulse earbuds 3× spike — real or failure?",
    severity: "S1",
    behaviourType: "festival-verdict",
    cohortId: "SKU-FEST-BUDS",
    cohort: "SKU-FEST-BUDS",
    baselineCellId: "sale-scaled",
    deviationStat: "3× vs sale-scaled baseline",
    onsetTs: "Today 11:05",
    onset: "Today 11:05",
    causeClass: "payment-gateway",
    confidence: "High",
    impactValue: "Conservative tier",
    impactRupee: "Payment-gateway failure pattern",
    ruledOut: ["organic demand surge"],
    honestyLine: "Detection: order spike · Verdict: failure voice + aligned account signal",
    ownerPersona: "Trust & Safety + Operations",
    signatureType: "E",
    stats: '"Payment deducted, no order" corroboration · account signal aligned',
    aiVerdict: "Payment-gateway failure — not demand. Prepare verified incident packet.",
    screenId: "festival-monitor",
    drillKind: "festival",
    regimeBadge: "Sale window — verified failure",
    actions: [{ actionLabel: "Prepare", routedOwner: "Trust & Safety + Operations", gated: false, status: "draft" }],
  },
  {
    signalId: "T2-12",
    cardId: "T2-12",
    title: "Nova kurta — colour/shade aspect rising",
    severity: "S2",
    behaviourType: "aspect-cliff",
    cohortId: "SKU-NOVA-KURTA",
    cohort: "SKU-NOVA-KURTA",
    baselineCellId: "aspect-mix",
    deviationStat: "19% aspect share vs 6% trailing",
    onsetTs: "Wed 08:15",
    onset: "Wed 08:15",
    causeClass: "catalogue-quality",
    confidence: "Med-High",
    impactValue: "Conversion −6%",
    impactRupee: "Correlation band on conversion",
    ruledOut: ["star average move"],
    honestyLine: "Directional join — aspect slope vs trailing mix, not star average",
    ownerPersona: "Catalogue + CX",
    signatureType: "F",
    stats: "Star steady 4.0 · conversion −6% (correlation band)",
    aiVerdict: "Leading indicator — shade mismatch rising before star rating moves.",
    screenId: "command-centre",
    drillKind: "signal",
    actions: [{ actionLabel: "Draft", routedOwner: "Catalogue/Quality", gated: false, status: "draft" }],
  },
  {
    signalId: "T2-19",
    cardId: "T2-19",
    title: "Stride shoe — do not promote",
    severity: "S2",
    behaviourType: "promo-gate",
    cohortId: "SKU-STRIDE-SHOE × SELL-QS",
    cohort: "SKU-STRIDE-SHOE × SELL-QS",
    baselineCellId: "promo-health",
    deviationStat: "ROAS 4.2 · returns 24% vs 18%",
    onsetTs: "Thu 10:00",
    onset: "Thu 10:00",
    causeClass: "promo-unhealthy",
    confidence: "High",
    impactValue: "₹3.4L",
    impactRupee: "₹3.4L redirectable spend",
    ruledOut: ["ROAS-only promote"],
    honestyLine: "Composite gate: returns band + sentiment slope + ROAS",
    ownerPersona: "Pricing / Retail-Media",
    signatureType: "G",
    stats: "ROAS 4.2 but returns 24% vs 18% · sentiment slope turned",
    aiVerdict: "Do-not-promote — LiSN advises, Priya decides on redirect.",
    screenId: "command-centre",
    drillKind: "signal",
    actions: [{ actionLabel: "Route", routedOwner: "Pricing / Retail-Media", gated: false, status: "draft" }],
  },
  {
    signalId: "T2-07",
    cardId: "T2-07",
    title: "QuickStyle — seller trust exposure",
    severity: "S1",
    behaviourType: "seller-trust",
    cohortId: "SELL-QS",
    cohort: "SELL-QS",
    baselineCellId: "seller-concentration",
    deviationStat: "23% concentration vs 25% cap",
    onsetTs: "Mon 09:00",
    onset: "Mon 09:00",
    causeClass: "cancel-after-wait",
    confidence: "High",
    impactValue: "₹52L",
    impactRupee: "₹52L GMV at risk (board total, 3 sellers)",
    ruledOut: [],
    honestyLine: "Detection: cancel-after-wait clusters · Verdict: care + review voice",
    ownerPersona: "Seller-Brand",
    signatureType: "C",
    stats: "Cancel-after-wait clusters · 23% concentration (within 25% cap)",
    aiVerdict: "Top seller row — customer-backed GMV exposure, not raw breach counts.",
    screenId: "seller-trust",
    drillKind: "sellers",
    actions: [{ actionLabel: "Draft", routedOwner: "Seller-Brand", gated: true, status: "draft" }],
  },
  {
    signalId: "T2-15",
    cardId: "T2-15",
    title: "Quick-commerce defect wave",
    severity: "S2",
    behaviourType: "defect-wave",
    cohortId: "QCOM-PERISHABLE",
    cohort: "QCOM dark-store slice",
    baselineCellId: "qcom-returns",
    deviationStat: "Return initiation spike",
    onsetTs: "Today 07:30",
    onset: "Today 07:30",
    causeClass: "care-defect",
    confidence: "Med-High",
    impactValue: "Early recall signal",
    impactRupee: "Perishable defect theme",
    ruledOut: [],
    honestyLine: "Return initiation co-moving with care defect transcript theme",
    ownerPersona: "Operations",
    signatureType: "E",
    stats: "Return-initiation spike + care defect theme alignment",
    aiVerdict: "Quick-commerce colour — early recall before ops dashboard moves.",
    screenId: "festival-monitor",
    drillKind: "festival",
    actions: [{ actionLabel: "Prepare", routedOwner: "Operations", gated: false, status: "draft" }],
  },
  {
    signalId: "T2-17",
    cardId: "T2-17",
    title: "Stockout — lost demand estimate",
    severity: "S2",
    behaviourType: "lost-demand",
    cohortId: "QCOM-SKU-GROC",
    cohort: "Quick-commerce grocery SKU",
    baselineCellId: "stockout",
    deviationStat: "Fill-rate dip",
    onsetTs: "Today 06:45",
    onset: "Today 06:45",
    causeClass: "stockout",
    confidence: "Med-High",
    impactValue: "Lost GMV + ad waste",
    impactRupee: "Switching voice to competitor",
    ruledOut: [],
    honestyLine: "Null-search + switching voice join",
    ownerPersona: "Operations / Supply",
    signatureType: "H",
    stats: "Lost GMV estimate · wasted ad spend · switching voice",
    aiVerdict: "Replenish / pause ads draft — demand-sized buying proposal.",
    screenId: "command-centre",
    drillKind: "signal",
    actions: [{ actionLabel: "Draft", routedOwner: "Operations / Supply", gated: false, status: "draft" }],
  },
  {
    signalId: "SUPPRESSED-TEE",
    cardId: "SUPPRESSED-TEE",
    title: "4× tee spike — expected demand, suppressed",
    severity: "S3",
    behaviourType: "suppressed",
    cohortId: "SKU-FEST-TEE",
    cohort: "SKU-FEST-TEE",
    baselineCellId: "sale-scaled",
    deviationStat: "4× vs sale-day baseline",
    onsetTs: "Today 10:20",
    onset: "Today 10:20",
    causeClass: "expected-demand",
    confidence: "High",
    impactValue: "—",
    impactRupee: "No failure voice",
    ruledOut: ["payment failure", "fraud"],
    honestyLine: "Spike vs sale-scaled baseline — no failure voice corroboration",
    ownerPersona: "—",
    signatureType: "E",
    stats: "4× spike · no failure voice · suppressed for credibility",
    aiVerdict: "Expected sale-day demand — distillation held this below the rail.",
    screenId: "command-centre",
    drillKind: "signal",
    suppressed: true,
    regimeBadge: "Sale window — expected demand",
    actions: [],
  },
  {
    signalId: "ADVISORY-LANE",
    cardId: "ADVISORY-LANE",
    title: "Tier-2 lane RTO — advisory, watch",
    severity: "S3",
    behaviourType: "advisory",
    cohortId: "LANE-T2-IND",
    cohort: "LANE-T2-IND",
    baselineCellId: "lane-t2",
    deviationStat: "Sparse sample",
    onsetTs: "—",
    onset: "—",
    causeClass: "thin-voice",
    confidence: "Low",
    impactValue: "—",
    impactRupee: "Thin voice sample",
    ruledOut: [],
    honestyLine: "Sparse sample / thin voice — cohort-level watch only",
    ownerPersona: "—",
    signatureType: "D",
    stats: "Insufficient voice density for verdict",
    aiVerdict: "Watch — no action until sample thickens.",
    screenId: "lane-rto",
    drillKind: "lanes",
    advisory: true,
    actions: [],
  },
];

export const EVIDENCE_PACKS: Record<string, EvidencePack> = {
  "T2-02": {
    verbatims: [
      '"Chest feels narrow vs the size chart — ordered M, fits like S."',
      '"Fabric quality fine but sizing off by ~2 cm on chest."',
      '"Returning — chart says 40 inch chest, garment measures ~37."',
    ],
    resolvedOrderTrail: [
      "Order #8821041 — Aura shirt M — return initiated — reason: size",
      "Order #8820899 — Aura shirt L — return initiated — reason: size",
      "Order #8819772 — Aura shirt M — exchange requested → return",
    ],
    provenance: "Return free-text + reviews corpus · cohort-level join",
  },
  "T2-26": {
    verbatims: [
      '"Rider did not attempt delivery — marked undelivered."',
      '"Waited 3 days — package shows out for delivery but never came."',
      '"NCR outbound — same lane issue as last week."',
    ],
    resolvedOrderTrail: [
      "Lane DEL-NCR-O — 412 RTO events this week",
      "70% transcripts tagged delivery-theme",
    ],
    provenance: "Lane voice cohort · fulfilment events",
  },
  "T2-07": {
    verbatims: [
      '"Cancelled after I waited 3 days for dispatch."',
      '"Seller accepted order then cancelled — no explanation."',
    ],
    resolvedOrderTrail: ["SELL-QS — 23% category GMV concentration", "ODR near line · repeat-contact elevated"],
    provenance: "Care + review voice · seller-keyed",
  },
  "T2-28": {
    verbatims: [
      '"Payment deducted but no order confirmation."',
      '"Money taken, order not showing in app."',
    ],
    resolvedOrderTrail: ["Gateway timeout cluster 11:00–11:45", "Account signal aligned"],
    provenance: "Failure voice + payment status feed",
  },
};

export const CAUSE_CODES = [
  { code: "RC-REMORSE", label: "Buyer remorse", pct: 64 },
  { code: "RC-SIZE", label: "Fixable sizing", pct: 28 },
  { code: "RC-QUAL", label: "Quality", pct: 5 },
  { code: "RC-OTHER", label: "Other", pct: 3 },
];

export const SELLER_ROWS = [
  {
    sellerId: "SELL-QS",
    name: "QuickStyle",
    tier: "Gold",
    gmvExposure: "₹22L",
    complaintCluster: "Cancel-after-wait",
    repeatContact: "18%",
    slaBreach: "Dispatch SLA 64%",
    concentrationPct: 23,
  },
  {
    sellerId: "SELL-TF",
    name: "TrendForge",
    tier: "Silver",
    gmvExposure: "₹18L",
    complaintCluster: "Sizing disputes",
    repeatContact: "12%",
    slaBreach: "ODR 2.1%",
    concentrationPct: 19,
  },
  {
    sellerId: "SELL-MX",
    name: "MetroEx",
    tier: "Silver",
    gmvExposure: "₹12L",
    complaintCluster: "Late dispatch",
    repeatContact: "9%",
    slaBreach: "Late ship 11%",
    concentrationPct: 12,
  },
];

export function getSignalById(id: string): CategorySignalView | undefined {
  return SIGNALS.find((s) => s.signalId === id);
}

export function getSignalsForRail(order: string[]): CategorySignalView[] {
  const map = new Map(SIGNALS.map((s) => [s.signalId, s]));
  return order.map((id) => map.get(id)).filter((s): s is CategorySignalView => Boolean(s));
}

export function severityRank(sev: CategorySignalView["severity"]): number {
  if (sev === "S1") return 0;
  if (sev === "S2") return 1;
  return 2;
}

export function buildInitialAppState(): AppState {
  const suppressed = SIGNALS.filter((s) => s.suppressed);
  const signals: Signal[] = SIGNALS.map(({ ...s }) => s);

  return {
    personaId: "category-head",
    theme: "light",
    scope: {
      category: "Fashion + Quick-Commerce Grocery",
      laneId: "LANE-DEL-NCR-O",
      window: "normal",
    },
    signals,
    baselines: {},
    evidencePacks: EVIDENCE_PACKS,
    kpis: {
      contribution: 2.42,
      returnRate: 31,
      recoverableMargin: 6.0,
      sellerRisk: 3,
      conductFlag: true,
    },
    rail: {
      orderedSignalIds: [...DEFAULT_RAIL_ORDER],
      suppressed,
    },
    ui: {
      selectedSignalId: null,
      openDrill: null,
      dayGeneratorActive: false,
    },
    audit: [],
  };
}

export const AI_WEEK_RESPONSE =
  "Re-ranked for Priya: Aura shirt recoverable margin first, then Delhi-NCR lane RTO, then festival payment failure. Suppressed tee spike stays visible for credibility. No actions fired — open each signal to draft.";

export const CX_PERSONA_RAIL_ORDER = [
  "T2-02",
  "T2-12",
  "T2-19",
  "T2-26",
  "T2-07",
  "T2-28",
  "T2-15",
  "T2-17",
  "SUPPRESSED-TEE",
  "ADVISORY-LANE",
];
