"""Hand-written fictional records for the V3 demo: 12 priority personas (E2, E3) and 20 L2 escalation emails (A1).

Rules: fictional only. No real names, no celebrities, no officials, no occupation labels. Masked ids only. A cohort comes
from the bank's own relationship tiers and lists; "high impact" is a property of a complaint, never of a person.
"""

# Steps with "event": True are system events shown in the trail (e.g. a card decline); they are not interactions.

PERSONAS = [
    {
        "masked_id": "XXXX4821",
        "persona": "Persona 1",
        "descriptor": "Private Banking relationship, 14 years, Mumbai",
        "segment": "Private",
        "cohorts": ["priority_a", "uhni"],
        "products": ["cards", "accounts", "home_loans", "digital"],
        "rm_id": "RM-017",
        "proxy_contacts": 1,
        "rm_notified": False,
        "story": True,
        "trail": [
            {
                "event": True,
                "at": "2026-09-27T19:42+05:30",
                "channel": "system",
                "product": "cards",
                "theme": "card_limit",
                "summary": "Card declined at a hotel abroad: international usage limit reached.",
            },
            {
                "at": "2026-09-27T19:44+05:30",
                "channel": "ivr_bot",
                "product": "cards",
                "theme": "card_limit",
                "summary": "Automated call read out the decline reason. The customer asked for a limit change; the bot could not make it.",
                "sentiment": "negative",
                "status": "closed",
                "closed_at": "2026-09-27T19:47+05:30",
                "first_response_at": "2026-09-27T19:44+05:30",
                "flag_set": True,
            },
            {
                "at": "2026-09-27T20:31+05:30",
                "channel": "email",
                "sender": "proxy",
                "product": "cards",
                "theme": "card_limit",
                "summary": "Email from the customer's assistant, on their behalf: the card was declined twice abroad; please raise the limit tonight. Linked through the bank's own contact records.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": None,
            },
            {
                "at": "2026-09-28T10:12+05:30",
                "channel": "inbound_voice",
                "product": "accounts",
                "theme": "care_unreachable",
                "summary": "Called the accounts helpline to move funds for the same payment; asked why no one had called back about the card.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": "2026-09-28T10:12+05:30",
                "flag_follows": True,
            },
            {
                "at": "2026-09-28T13:05+05:30",
                "channel": "social_inbox",
                "product": "cards",
                "theme": "complaint_handling",
                "summary": "Public reply to the bank's care handle: two days, three contacts, still no answer. Linked through a verified contact the bank already holds.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": None,
                "high_impact": ["public_reach"],
            },
            {
                "at": "2026-09-28T18:20+05:30",
                "channel": "inbound_voice",
                "product": "cards",
                "theme": "card_limit",
                "summary": "Repeat call: limit raised for 48 hours; the agent promised a callback on the declines. No callback logged.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": "2026-09-28T18:20+05:30",
            },
        ],
    },
    {
        "masked_id": "XXXX2317",
        "persona": "Persona 2",
        "descriptor": "Private Banking relationship, 9 years, Delhi",
        "segment": "Private",
        "cohorts": ["priority_a", "uhni"],
        "products": ["cards", "accounts", "digital"],
        "rm_id": "RM-042",
        "proxy_contacts": 1,
        "rm_notified": True,
        "trail": [
            {
                "at": "2026-09-26T11:05+05:30",
                "channel": "email",
                "product": "accounts",
                "theme": "complaint_handling",
                "summary": "Complaint about a closed service request that was not resolved; names the RBI Ombudsman as the next step.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": "2026-09-26T16:40+05:30",
                "high_impact": ["regulator_named"],
            },
            {
                "at": "2026-09-27T09:30+05:30",
                "channel": "outbound_voice",
                "product": "accounts",
                "theme": "complaint_handling",
                "summary": "RM called back and logged a fresh request; resolution promised within two working days.",
                "sentiment": "neutral",
                "status": "open",
                "first_response_at": "2026-09-27T09:30+05:30",
            },
        ],
    },
    {
        "masked_id": "XXXX3390",
        "persona": "Persona 3",
        "descriptor": "Imperia relationship, 6 years, Bengaluru",
        "segment": "Imperia",
        "cohorts": ["priority_b", "hni"],
        "products": ["cards", "accounts", "payzapp", "digital"],
        "rm_id": "RM-066",
        "proxy_contacts": 0,
        "rm_notified": False,
        "cohort_added_at": "2026-09-25T15:10+05:30",
        "cohort_added_by": "lisn_suggested_bank_confirmed",
        "trail": [
            {
                "at": "2026-09-24T21:14+05:30",
                "channel": "chat",
                "product": "payzapp",
                "theme": "failed_txn_reversal",
                "summary": "UPI payment debited but failed; reversal not received after the T+1 timeline.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": "2026-09-24T21:15+05:30",
            },
            {
                "at": "2026-09-27T12:02+05:30",
                "channel": "inbound_voice",
                "product": "cards",
                "theme": "card_variant_migration",
                "summary": "Asked why the card was moved to a new variant without consent; says fees now apply.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": "2026-09-27T12:02+05:30",
            },
        ],
    },
    {
        "masked_id": "XXXX1576",
        "persona": "Persona 4",
        "descriptor": "Private Banking relationship, 21 years, Chennai",
        "segment": "Private",
        "cohorts": ["priority_a", "uhni"],
        "products": ["cards", "accounts", "home_loans", "insurance", "digital"],
        "rm_id": "RM-008",
        "proxy_contacts": 1,
        "rm_notified": True,
        "trail": [
            {
                "at": "2026-09-22T10:00+05:30",
                "channel": "email",
                "sender": "proxy",
                "product": "home_loans",
                "theme": "loan_closure_documents",
                "summary": "Email from the customer's office: property documents not returned three weeks after the loan was closed.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": "2026-09-22T15:30+05:30",
            },
        ],
    },
    {
        "masked_id": "XXXX5203",
        "persona": "Persona 5",
        "descriptor": "Private Banking relationship, 4 years, Pune",
        "segment": "Private",
        "cohorts": ["uhni"],
        "products": ["cards", "accounts", "digital"],
        "rm_id": "RM-091",
        "proxy_contacts": 0,
        "rm_notified": False,
        "trail": [
            {
                "at": "2026-09-28T22:48+05:30",
                "channel": "chat",
                "product": "digital",
                "theme": "device_security_block",
                "summary": "App blocked on a new phone with a security alert; cannot approve a large transfer.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": "2026-09-28T22:49+05:30",
            },
        ],
    },
    {
        "masked_id": "XXXX2688",
        "persona": "Persona 6",
        "descriptor": "Imperia relationship, 11 years, Hyderabad",
        "segment": "Imperia",
        "cohorts": ["priority_b", "hni"],
        "products": ["cards", "accounts", "auto_loans", "digital"],
        "rm_id": "RM-073",
        "proxy_contacts": 0,
        "rm_notified": False,
        "trail": [
            {
                "at": "2026-09-23T16:20+05:30",
                "channel": "inbound_voice",
                "product": "cards",
                "theme": "dispute_chargeback",
                "summary": "Disputed a foreign merchant charge; no update since the dispute was raised.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": "2026-09-23T16:20+05:30",
            },
            {
                "at": "2026-09-28T09:40+05:30",
                "channel": "branch",
                "product": "auto_loans",
                "theme": "loan_servicing",
                "summary": "Visited the branch about the car-loan EMI date; mentioned the open card dispute.",
                "sentiment": "neutral",
                "status": "closed",
                "closed_at": "2026-09-28T10:05+05:30",
                "first_response_at": "2026-09-28T09:40+05:30",
            },
        ],
    },
    {
        "masked_id": "XXXX4077",
        "persona": "Persona 7",
        "descriptor": "Private Banking relationship, 17 years, Kolkata",
        "segment": "Private",
        "cohorts": ["priority_a", "uhni"],
        "products": ["cards", "accounts", "digital"],
        "rm_id": "RM-025",
        "proxy_contacts": 1,
        "rm_notified": True,
        "trail": [
            {
                "at": "2026-09-20T12:15+05:30",
                "channel": "email",
                "product": "cards",
                "theme": "closure_requests",
                "summary": "Asked to close a supplementary card; closure confirmation not received.",
                "sentiment": "negative",
                "status": "closed",
                "closed_at": "2026-09-26T14:00+05:30",
                "first_response_at": "2026-09-20T17:10+05:30",
            },
        ],
    },
    {
        "masked_id": "XXXX1942",
        "persona": "Persona 8",
        "descriptor": "Imperia relationship, 8 years, Ahmedabad",
        "segment": "Imperia",
        "cohorts": ["hni"],
        "products": ["cards", "accounts", "personal_loans", "digital"],
        "rm_id": "RM-054",
        "proxy_contacts": 0,
        "rm_notified": False,
        "trail": [
            {
                "at": "2026-09-28T14:30+05:30",
                "channel": "whatsapp",
                "product": "personal_loans",
                "theme": "fees_charges_bank",
                "summary": "Questioned a foreclosure charge on a personal loan that was not in the sanction letter.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": None,
            },
        ],
    },
    {
        "masked_id": "XXXX3815",
        "persona": "Persona 9",
        "descriptor": "Private Banking relationship, 12 years, Mumbai",
        "segment": "Private",
        "cohorts": ["priority_b", "uhni"],
        "products": ["cards", "accounts", "insurance", "digital"],
        "rm_id": "RM-017",
        "proxy_contacts": 1,
        "rm_notified": False,
        "trail": [
            {
                "at": "2026-09-25T11:45+05:30",
                "channel": "email",
                "sender": "proxy",
                "product": "insurance",
                "theme": "mis_selling",
                "summary": "Email from the customer's assistant: an insurance policy was added to the account without a clear explanation.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": "2026-09-26T10:00+05:30",
                "high_impact": ["legal_language"],
            },
        ],
    },
    {
        "masked_id": "XXXX2950",
        "persona": "Persona 10",
        "descriptor": "Imperia relationship, 3 years, Gurugram",
        "segment": "Imperia",
        "cohorts": ["hni"],
        "products": ["cards", "accounts", "payzapp", "digital"],
        "rm_id": "RM-101",
        "proxy_contacts": 0,
        "rm_notified": False,
        "trail": [
            {
                "at": "2026-09-27T08:55+05:30",
                "channel": "chat",
                "product": "cards",
                "theme": "rewards_value",
                "summary": "Reward points on travel spends lower than expected after the cap change.",
                "sentiment": "negative",
                "status": "closed",
                "closed_at": "2026-09-27T11:30+05:30",
                "first_response_at": "2026-09-27T08:56+05:30",
            },
        ],
    },
    {
        "masked_id": "XXXX5566",
        "persona": "Persona 11",
        "descriptor": "Private Banking relationship, 19 years, Bengaluru",
        "segment": "Private",
        "cohorts": ["priority_a", "uhni"],
        "products": ["cards", "accounts", "digital"],
        "rm_id": "RM-033",
        "proxy_contacts": 1,
        "rm_notified": False,
        "trail": [
            {
                "at": "2026-09-28T19:10+05:30",
                "channel": "inbound_voice",
                "product": "cards",
                "theme": "unauthorised_txn",
                "summary": "Reported two card transactions the customer did not make; card blocked, shadow credit pending.",
                "sentiment": "negative",
                "status": "open",
                "first_response_at": "2026-09-28T19:10+05:30",
            },
        ],
    },
    {
        "masked_id": "XXXX1318",
        "persona": "Persona 12",
        "descriptor": "Imperia relationship, 7 years, Kochi",
        "segment": "Imperia",
        "cohorts": ["priority_b", "hni"],
        "products": ["cards", "accounts", "home_loans", "digital"],
        "rm_id": "RM-060",
        "proxy_contacts": 0,
        "rm_notified": True,
        "trail": [
            {
                "at": "2026-09-21T10:25+05:30",
                "channel": "email",
                "product": "accounts",
                "theme": "kyc_updates",
                "summary": "Re-KYC documents submitted twice; account still shows as restricted.",
                "sentiment": "negative",
                "status": "closed",
                "closed_at": "2026-09-28T12:00+05:30",
                "first_response_at": "2026-09-21T15:00+05:30",
            },
        ],
    },
]

BUCKETS = {
    "reply_status": "Reply with backend status",
    "call_today": "Call today (deliverable breaking)",
    "escalate": "Escalate (no backend movement, deliverable broken)",
    "proactive_status": "Proactive status message",
    "close_confirm": "Close with confirmation",
    "route_owner": "Route to another product owner",
}

ESCALATION_EMAILS = [
    {
        "id": "L2-01",
        "received_at": "2026-09-28T09:12+05:30",
        "sender": "customer",
        "product": "cards",
        "theme": "card_dispatch",
        "language": "English",
        "subject": "Replacement card still not delivered",
        "body": "I requested a replacement card on 16 September. The tracking page has not moved for a week. Please tell me where the card is.",
        "backend_status": "Card dispatched 27 Sep; courier shows out for delivery 29 Sep.",
        "bucket": "reply_status",
        "draft_reply": "Thank you for writing to us. Your replacement card was dispatched on 27 September and the courier shows it out for delivery today, 29 September. We will confirm once it is delivered. We are sorry for the wait.",
    },
    {
        "id": "L2-02",
        "received_at": "2026-09-28T10:40+05:30",
        "sender": "customer",
        "product": "payzapp",
        "theme": "failed_txn_reversal",
        "language": "Hinglish",
        "subject": "UPI paisa kat gaya, wapas nahi aaya",
        "body": "26 September ko UPI payment fail hua, paisa account se kat gaya. Abhi tak reversal nahi aaya. Complaint pehle bhi kiya tha.",
        "backend_status": "Reversal credited 28 Sep, 18:05. Compensation for one day of delay due.",
        "bucket": "reply_status",
        "draft_reply": "Thank you for writing to us. The failed UPI payment of 26 September was reversed to your account on 28 September at 18:05. As the reversal was one day late, the compensation due under the RBI timeline will be credited separately. We are sorry for the inconvenience.",
    },
    {
        "id": "L2-03",
        "received_at": "2026-09-28T12:05+05:30",
        "sender": "proxy",
        "product": "accounts",
        "theme": "kyc_updates",
        "language": "English",
        "subject": "On behalf of our director: account restriction after re-KYC",
        "body": "Writing on behalf of the account holder. Re-KYC documents were submitted at the branch on 19 September. The account still shows as restricted. Please advise.",
        "backend_status": "Re-KYC verified 28 Sep; restriction lifted 28 Sep, 17:30.",
        "bucket": "reply_status",
        "draft_reply": "Thank you for writing to us. The re-KYC documents were verified on 28 September and the restriction on the account was lifted the same day at 17:30. The account is now fully active. We will reply to the account holder's registered email as well.",
    },
    {
        "id": "L2-04",
        "received_at": "2026-09-28T15:22+05:30",
        "sender": "customer",
        "product": "home_loans",
        "theme": "loan_processing",
        "language": "English",
        "subject": "Disbursal date for my home loan",
        "body": "My builder is asking for the next instalment. The disbursal was approved last week. When will it be paid?",
        "backend_status": "Disbursal scheduled 30 Sep after the technical visit report.",
        "bucket": "reply_status",
        "draft_reply": "Thank you for writing to us. The next disbursal on your home loan is scheduled for 30 September, following the technical visit report. We will send the payment confirmation to you and to the builder once it is made.",
    },
    {
        "id": "L2-05",
        "received_at": "2026-09-28T17:48+05:30",
        "sender": "customer",
        "product": "cards",
        "theme": "reward_redemption",
        "language": "Hinglish",
        "subject": "Voucher redeem kiya, mila nahi",
        "body": "Reward points se voucher redeem kiya 22 September ko. Points kat gaye par voucher email mein nahi aaya.",
        "backend_status": "Voucher issued 28 Sep; resent to registered email.",
        "bucket": "reply_status",
        "draft_reply": "Thank you for writing to us. The voucher you redeemed on 22 September was issued on 28 September and has been sent again to your registered email address. Please check your inbox, including the spam folder. We are sorry for the delay.",
    },
    {
        "id": "L2-06",
        "received_at": "2026-09-27T11:30+05:30",
        "sender": "customer",
        "product": "cards",
        "theme": "closure_requests",
        "language": "English",
        "subject": "Card closure request ignored",
        "body": "I asked for my credit card to be closed on 19 September. It is still active and I have been charged an annual fee.",
        "backend_status": "Closure request open; day 7 of 7 working days today.",
        "bucket": "call_today",
    },
    {
        "id": "L2-07",
        "received_at": "2026-09-27T14:10+05:30",
        "sender": "customer",
        "product": "cards",
        "theme": "unauthorised_txn",
        "language": "English",
        "subject": "Fraudulent transactions: shadow credit",
        "body": "I reported two transactions I did not make on 19 September. I was told I would get a temporary credit. Nothing yet.",
        "backend_status": "Shadow credit pending; day 8 of 10 working days.",
        "bucket": "call_today",
    },
    {
        "id": "L2-08",
        "received_at": "2026-09-28T08:50+05:30",
        "sender": "proxy",
        "product": "home_loans",
        "theme": "loan_closure_documents",
        "language": "English",
        "subject": "Property documents after loan closure",
        "body": "Writing for the borrower. The loan was closed on 1 September. The original property documents have not been returned.",
        "backend_status": "Documents at the central vault; day 28 of 30 calendar days.",
        "bucket": "call_today",
    },
    {
        "id": "L2-09",
        "received_at": "2026-09-28T19:05+05:30",
        "sender": "customer",
        "product": "accounts",
        "theme": "account_freeze",
        "language": "Hinglish",
        "subject": "Account freeze kyun hua",
        "body": "Mera salary account achanak debit freeze ho gaya. Branch ne bola email karo. Rent aur EMI dono atke hain.",
        "backend_status": "Freeze review opened 26 Sep; bank TAT 3 working days ends today.",
        "bucket": "call_today",
    },
    {
        "id": "L2-10",
        "received_at": "2026-09-26T10:15+05:30",
        "sender": "customer",
        "product": "cards",
        "theme": "dispute_chargeback",
        "language": "English",
        "subject": "Dispute raised in August, no update",
        "body": "I disputed a charge on 18 August. Two follow-ups later, I have no update. I will approach the RBI Ombudsman if this is not resolved.",
        "backend_status": "No movement since 24 Aug; merchant response not chased.",
        "bucket": "escalate",
    },
    {
        "id": "L2-11",
        "received_at": "2026-09-27T16:35+05:30",
        "sender": "customer",
        "product": "accounts",
        "theme": "complaint_handling",
        "language": "English",
        "subject": "Complaint closed without resolution, third time",
        "body": "This is the third time my complaint has been closed without anything being fixed. The charge is still on my statement.",
        "backend_status": "Closed twice without reversal; charge still applied.",
        "bucket": "escalate",
    },
    {
        "id": "L2-12",
        "received_at": "2026-09-28T11:55+05:30",
        "sender": "customer",
        "product": "personal_loans",
        "theme": "credit_report",
        "language": "English",
        "subject": "Wrong entry on my credit report",
        "body": "My personal loan was closed in June but my credit report still shows it as active. My home loan application is stuck because of it.",
        "backend_status": "Correction not sent to the bureau; day 34 of 30.",
        "bucket": "escalate",
    },
    {
        "id": "L2-13",
        "received_at": "2026-09-28T13:20+05:30",
        "sender": "customer",
        "product": "cards",
        "theme": "card_application",
        "language": "English",
        "subject": "Card application status",
        "body": "I applied for a credit card two weeks ago. The status page says under process. How much longer?",
        "backend_status": "Verification complete; approval expected 30 Sep.",
        "bucket": "proactive_status",
    },
    {
        "id": "L2-14",
        "received_at": "2026-09-28T16:02+05:30",
        "sender": "customer",
        "product": "payzapp",
        "theme": "refund_delay",
        "language": "Hinglish",
        "subject": "Refund abhi tak nahi aaya",
        "body": "Merchant ne 20 September ko refund process kiya. Bank mein abhi tak credit nahi hua.",
        "backend_status": "Refund received from the network 28 Sep; credit in the next batch.",
        "bucket": "proactive_status",
    },
    {
        "id": "L2-15",
        "received_at": "2026-09-28T18:30+05:30",
        "sender": "customer",
        "product": "auto_loans",
        "theme": "loan_processing",
        "language": "English",
        "subject": "Two-wheeler loan approval",
        "body": "My two-wheeler loan was approved but the dealer has not received the payment.",
        "backend_status": "Payment released 28 Sep; dealer credit on 29 Sep.",
        "bucket": "proactive_status",
    },
    {
        "id": "L2-16",
        "received_at": "2026-09-25T09:40+05:30",
        "sender": "customer",
        "product": "cards",
        "theme": "card_fees_charges",
        "language": "English",
        "subject": "Annual fee reversal",
        "body": "I met the spend condition for the fee waiver but was charged the annual fee.",
        "backend_status": "Fee reversed 27 Sep; customer not yet informed.",
        "bucket": "close_confirm",
    },
    {
        "id": "L2-17",
        "received_at": "2026-09-26T12:25+05:30",
        "sender": "customer",
        "product": "digital",
        "theme": "login_mpin",
        "language": "Hinglish",
        "subject": "App login nahi ho raha",
        "body": "Naya phone liya, app mein login nahi ho raha. MPIN reset bhi fail ho raha hai.",
        "backend_status": "Device binding reset 27 Sep; customer logged in 27 Sep, 20:14.",
        "bucket": "close_confirm",
    },
    {
        "id": "L2-18",
        "received_at": "2026-09-27T10:05+05:30",
        "sender": "customer",
        "product": "accounts",
        "theme": "statements_documents",
        "language": "English",
        "subject": "Interest certificate",
        "body": "I need the interest certificate for my fixed deposits for a visa application.",
        "backend_status": "Certificate emailed 27 Sep.",
        "bucket": "close_confirm",
    },
    {
        "id": "L2-19",
        "received_at": "2026-09-28T11:10+05:30",
        "sender": "customer",
        "product": "accounts",
        "theme": "mis_selling",
        "language": "English",
        "subject": "Insurance added without my consent",
        "body": "An insurance premium has been debited from my savings account. I never agreed to buy a policy.",
        "backend_status": "Policy sold through the branch; insurance product owner to review.",
        "bucket": "route_owner",
    },
    {
        "id": "L2-20",
        "received_at": "2026-09-28T20:45+05:30",
        "sender": "customer",
        "product": "digital",
        "theme": "unsolicited_calls",
        "language": "English",
        "subject": "Too many sales calls",
        "body": "I receive loan offer calls every day after using the app. How did they get my number and how do I stop them?",
        "backend_status": "Consent and preference records sit with Compliance.",
        "bucket": "route_owner",
    },
]
